PATH=$PATH:$HOME/.local/bin:$HOME/bin

export PATH

export TMP=/tmp
export TMPDIR=$TMP

export ORACLE_HOSTNAME=dwhnode05
export ORACLE_UNQNAME=dwhdb05
export ORACLE_BASE=/data01/app/oracle
export ORACLE_HOME=$ORACLE_BASE/product/19.0.0/dbhome_1
export ORA_INVENTORY=/data01/app/oraInventory
export ORACLE_SID=dwhdb05
export DATA_DIR=/data01/oradata

export PATH=/usr/sbin:/usr/local/bin:$PATH
export PATH=$ORACLE_HOME/bin:$PATH

export LD_LIBRARY_PATH=$ORACLE_HOME/lib:/lib:/usr/lib
export CLASSPATH=$ORACLE_HOME/jlib:$ORACLE_HOME/rdbms/jlib



FILE_NAME="EVCREC_EXT"  export FILE_NAME

##echo "-------------------------------- $1 --------------------------------"
echo "Create table started at `date \"+%D %T\"`"

SYN_TYPE="EVCREC01" export SYN_TYPE
echo $SYN_TYPE

sqlplus -s <<EOF
dwh_user/dwh_user_123
set feedback off
drop table $FILE_NAME
/
create table $FILE_NAME
(
  ER01_SERIAL_NUMBER             VARCHAR2(256 BYTE),
  ER02_REGION_ID                 VARCHAR2(256 BYTE),
  ER03_MSISDN_DEALER             VARCHAR2(256 BYTE),
  ER04_INITIATOR_DEALER_ID       VARCHAR2(256 BYTE),
  ER05_INITIATOR_TEMPLATE_ID     VARCHAR2(256 BYTE),
  ER06_DEALER_NAME               VARCHAR2(256 BYTE),
  ER07_BRAND_TYPE                VARCHAR2(256 BYTE),
  ER08_USER_BRAND_TYPE           VARCHAR2(256 BYTE),
  ER09_PRICE                     VARCHAR2(256 BYTE),
  ER10_MSISDN                    VARCHAR2(256 BYTE),
  ER11_SUBSCRIBER_TYPE           VARCHAR2(256 BYTE),
  ER12_RECHARGE_DATE             VARCHAR2(256 BYTE),
  ER13_SERIAL_NUMBER_CARD        VARCHAR2(256 BYTE),
  ER14_RESPONSE_STATE            VARCHAR2(256 BYTE),
  ER15_TRANSACTION_STATUS        VARCHAR2(256 BYTE),
  ER16_ADJUST_STATUS             VARCHAR2(256 BYTE),
  ER17_ERROR_MESSAGE             VARCHAR2(256 BYTE),
  ER18_ACCESS_TYPE               VARCHAR2(256 BYTE),
  ER19_DEALER_DECREASE_MONEY     VARCHAR2(256 BYTE),
  ER20_ACCEPTOR_INCREASE_MONEY   VARCHAR2(256 BYTE),
  ER21_COMMISSION_RATE_RECHARGE  VARCHAR2(256 BYTE),
  ER22_SENDER_ID                 VARCHAR2(256 BYTE),
  ER23_ICCID                     VARCHAR2(256 BYTE),
  ER24_BALANCE_STOCK_ADJUSTOR    VARCHAR2(256 BYTE),
  ER25_RECHARGE_HANDLING_FEE     VARCHAR2(256 BYTE),
  ER26_BALANCE_AFTER_RECHARGE    VARCHAR2(256 BYTE),
  ER27_ENCRYPTED_MSISDN          VARCHAR2(256 BYTE),
  ER28_CELL_ID                   VARCHAR2(256 BYTE),
  ER29_SOURCE_MESSAGE            VARCHAR2(256 BYTE),
  ER30_DESTINATION_MESSAGE       VARCHAR2(256 BYTE),
  ER31_FUNCTION_ID               VARCHAR2(256 BYTE),
  ER32_ACCOUNT_INDEX             VARCHAR2(256 BYTE),
  ER33_OLD_BALANCE               VARCHAR2(256 BYTE),
  ER34_NEW_BALANCE               VARCHAR2(256 BYTE),
  ER35_NEW_VALIDITY              VARCHAR2(256 BYTE),
  ER36_RESERVED                  VARCHAR2(256 BYTE),
  ER37_ERROR_CODE                VARCHAR2(256 BYTE),
  ER38_RECHARGE_DURATION         VARCHAR2(256 BYTE),
  ER39_IN_RECHARGE_DURATION      VARCHAR2(256 BYTE),
  ER40_UPSTREAM_MSISDN           VARCHAR2(256 BYTE),
  ER41_UPSTREAM_NAME             VARCHAR2(256 BYTE),
  ER42_CELL_ID_RECHARGED_PARTY   VARCHAR2(256 BYTE),
  ER43_RESERVED                  VARCHAR2(256 BYTE),
  ER44_RESERVED                  VARCHAR2(256 BYTE),
  ER45_RESERVED                  VARCHAR2(256 BYTE),
  ER46_RESERVED                  VARCHAR2(256 BYTE),
  ER47_RESERVED                  VARCHAR2(256 BYTE),
  ER48_RESERVED                  VARCHAR2(256 BYTE),
  ER49_RESERVED                  VARCHAR2(256 BYTE),
  ER50_RESERVED                  VARCHAR2(256 BYTE)
)
ORGANIZATION EXTERNAL
  (  TYPE ORACLE_LOADER
     DEFAULT DIRECTORY EVCREC_DIR
     ACCESS PARAMETERS
       ( RECORDS DELIMITED by NEWLINE
        BADFILE     '$1.bad'
        DISCARDFILE '$1.dis'
        FIELDS TERMINATED BY '|'
 )
     LOCATION (EVCREC_DIR:'$1.unl')
  )
REJECT LIMIT UNLIMITED
NOPARALLEL
NOMONITORING
/
drop synonym  $SYN_TYPE
/
create synonym  $SYN_TYPE for $FILE_NAME
/
exit
EOF

echo "External table created"

