PATH=$PATH:$HOME/.local/bin:$HOME/bin

export PATH

export TMP=/tmp
export TMPDIR=$TMP

export ORACLE_HOSTNAME=dwhnode05
export ORACLE_UNQNAME=dwhdb05
export ORACLE_BASE=/data01/app/oracle
export ORACLE_HOME=$ORACLE_BASE/product/19.0.0/dbhome_1
export ORA_INVENTORY=/data01/app/oraInventory
export ORACLE_SID=dwhdb05
export DATA_DIR=/data01/oradata

export PATH=/usr/sbin:/usr/local/bin:$PATH
export PATH=$ORACLE_HOME/bin:$PATH

export LD_LIBRARY_PATH=$ORACLE_HOME/lib:/lib:/usr/lib
export CLASSPATH=$ORACLE_HOME/jlib:$ORACLE_HOME/rdbms/jlib



FILE_NAME="EVCTRA_EXT"  export FILE_NAME

##echo "-------------------------------- $1 --------------------------------"
echo "Create table started at `date \"+%D %T\"`"

SYN_TYPE="EVCTRA01" export SYN_TYPE
echo $SYN_TYPE

sqlplus -s <<EOF
dwh_user/dwh_user_123
set feedback off
drop table $FILE_NAME
/
create table $FILE_NAME
(
  ET01_SERIAL_NUMBER             VARCHAR2(256 BYTE),
  ET02_REGION_ID                 VARCHAR2(256 BYTE),
  ET03_MSISDN_DEALER             VARCHAR2(256 BYTE),
  ET04_INITIATOR_ID              VARCHAR2(256 BYTE),
  ET05_DEALER_NAME               VARCHAR2(256 BYTE),
  ET06_MSISDN_BENEFICIARY        VARCHAR2(256 BYTE),
  ET07_RECIPIENT_ID              VARCHAR2(256 BYTE),
  ET08_DEALER_NAME               VARCHAR2(256 BYTE),
  ET09_PRICE_TYPE                VARCHAR2(256 BYTE),
  ET10_AMOUNT_ROLLBACK           VARCHAR2(256 BYTE),
  ET11_SENDER_TRANSACTION        VARCHAR2(256 BYTE),
  ET12_TRANSFER_DATE             VARCHAR2(256 BYTE),
  ET13_STATE                     VARCHAR2(256 BYTE),
  ET14_ERROR_MESSAGE             VARCHAR2(256 BYTE),
  ET15_ACCESS_TYPE               VARCHAR2(256 BYTE),
  ET16_DEALER_DECREASE_MONEY     VARCHAR2(256 BYTE),
  ET17_ACCEPTOR_INCREASE_MONEY   VARCHAR2(256 BYTE),
  ET18_TRANSFER_COMMISSION_RATE  VARCHAR2(256 BYTE),
  ET19_SENDER_TEMPLATE_ID        VARCHAR2(256 BYTE),
  ET20_RECEIVER_TEMPLATE_ID      VARCHAR2(256 BYTE),
  ET21_SENDER_BALANCE_STOCK_ADJ  VARCHAR2(256 BYTE),
  ET22_TRANSFER_HANDLING_FEE     VARCHAR2(256 BYTE),
  ET23_TAX                       VARCHAR2(256 BYTE),
  ET24_RECEIVER_AFTER_ADJUSTOR   VARCHAR2(256 BYTE),
  ET25_RECEIVER_BEFORE_ADJUSTOR  VARCHAR2(256 BYTE),
  ET26_CELL_ID                   VARCHAR2(256 BYTE),
  ET27_SOURCE_MESSAGE            VARCHAR2(256 BYTE),
  ET28_DESTINATION_MESSAGE       VARCHAR2(256 BYTE),
  ET29_DENOMINATION_NUMBER       VARCHAR2(256 BYTE),
  ET30_QUANTITY                  VARCHAR2(256 BYTE),
  ET31_ACCOUNT_INDEX             VARCHAR2(256 BYTE),
  ET32_ACTUAL_PAYMENT_AMOUNT     VARCHAR2(256 BYTE),
  ET33_RESERVED                  VARCHAR2(256 BYTE),
  ET34_CELL_ID_TRANSFEREE        VARCHAR2(256 BYTE),
  ET35_RESERVED                  VARCHAR2(256 BYTE),
  ET36_BRAND_TYPE                VARCHAR2(256 BYTE),
  ET37_RESERVED                  VARCHAR2(256 BYTE)
)
ORGANIZATION EXTERNAL
  (  TYPE ORACLE_LOADER
     DEFAULT DIRECTORY EVCTRA_DIR
     ACCESS PARAMETERS
       ( RECORDS DELIMITED by NEWLINE
        BADFILE     '$1.bad'
        DISCARDFILE '$1.dis'
        FIELDS TERMINATED BY '|'
 )
     LOCATION (EVCTRA_DIR:'$1.unl')
  )
REJECT LIMIT UNLIMITED
NOPARALLEL
NOMONITORING
/
drop synonym  $SYN_TYPE
/
create synonym  $SYN_TYPE for $FILE_NAME
/
exit
EOF

echo "External table created"

