PATH=$PATH:$HOME/.local/bin:$HOME/bin

export PATH

export TMP=/tmp
export TMPDIR=$TMP

export ORACLE_HOSTNAME=dwhnode05
export ORACLE_UNQNAME=dwhdb05
export ORACLE_BASE=/data01/app/oracle
export ORACLE_HOME=$ORACLE_BASE/product/19.0.0/dbhome_1
export ORA_INVENTORY=/data01/app/oraInventory
export ORACLE_SID=dwhdb05
export DATA_DIR=/data01/oradata

export PATH=/usr/sbin:/usr/local/bin:$PATH
export PATH=$ORACLE_HOME/bin:$PATH

export LD_LIBRARY_PATH=$ORACLE_HOME/lib:/lib:/usr/lib
export CLASSPATH=$ORACLE_HOME/jlib:$ORACLE_HOME/rdbms/jlib


# This function changes the status of files where errors where encountered to 34
updateOnError()
{
sqlplus  -s <<EOF
dwh_user/dwh_user_123
SET echo off
SET head off
SET feedback off
REM "WHENEVER SQLERROR EXIT SQL.SQLCODE"
UPDATE cdr_head
   SET process_status=34
 WHERE file_name='$1'
   AND process_status=30
/
COMMIT
/
EXIT
EOF
}

# This function lists files after mediation and status is =30

get_smsc_files()
{

sqlplus  -s <<EOF
dwh_user/dwh_user_123
SET head off
SET feedback off
SET pagesize 0
SET verify off
SET linesize 400
SELECT '/data02/card/evcREC/process/'||','||'/data02/card/evcREC/process/'||file_name||','||file_name||','||file_id
  FROM cdr_head
 WHERE source='evcREC'
   AND process_status=30
   and rownum < 1000
/
EOF
}


createSMSCUpdate()
{
sqlplus  -s <<EOF
dwh_user/dwh_user_123
SET echo on
SET head off
SET feedback off
WHENEVER SQLERROR EXIT SQL.SQLCODE

UPDATE cdr_head
   SET process_status=32
 WHERE source='evcREC'
   AND file_name='$1'
/
COMMIT
/
EXIT
EOF
}

insertSMSCUpdate()
{
sqlplus  -s <<EOF
dwh_user/dwh_user_123
SET echo on
SET head off
SET feedback off
WHENEVER SQLERROR EXIT SQL.SQLCODE

INSERT INTO L1_EVCREC(PROCESSED_DATE,FILE_NAME,EVAC_01_SERIAL_NUMBER,EVAC_02_REGION_ID,EVAC_03_MSISDN_DEALER,EVAC_04_INITIATOR_DEALER_ID,EVAC_05_INITIATOR_TEMPLATE_ID,EVAC_06_DEALER_NAME,EVAC_07_BRAND_TYPE,EVAC_08_USER_BRAND_TYPE,EVAC_09_PRICE,EVAC_10_MSISDN,EVAC_11_SUBSCRIBER_TYPE,EVAC_12_RECHARGE_DATE,EVAC_13_SERIAL_NUMBER_RECHARGEABLE_CARD,EVAC_14_RESPONSE_STATE ,EVAC_15_TRANSACTION_STATUS,EVAC_16_ADJUST_STATUS,EVAC_17_ERROR_MESSAGE,EVAC_18_ACCESS_TYPE,EVAC_19_DEALER_ACTUAL_DECREASE_MONEY,EVAC_20_ACCEPTOR_ACTUAL_INCREASE_MONEY,EVAC_21_COMMISSION_RATE_RECHARGE,EVAC_22_SENDER_ID,EVAC_23_ICCID,EVAC_24_BALANCE_STOCK_ADJUSTOR,EVAC_25_RECHARGE_HANDLING_FEE,EVAC_26_BALANCE_AFTER_RECHARGE,EVAC_27_ENCRYPTED_MSISDN,EVAC_28_CELL_ID,EVAC_29_SOURCE_MESSAGE,EVAC_30_DESTINATION_MESSAGE,EVAC_31_FUNCTION_ID,EVAC_32_ACCOUNT_INDEX,EVAC_33_OLD_BALANCE,EVAC_34_NEW_BALANCE,EVAC_35_NEW_VALIDITY,EVAC_36_RESERVED,EVAC_37_ERROR_CODE,EVAC_38_RECHARGE_DURATION,EVAC_39_IN_RECHARGE_DURATION,EVAC_40_UPSTREAM_MSISDN,EVAC_41_UPSTREAM_NAME,EVAC_42_CELL_ID_RECHARGED_PARTY,EVAC_43_RESERVED,EVAC_44_RESERVED,EVAC_45_RESERVED,EVAC_46_RESERVED,EVAC_47_RESERVED,EVAC_48_RESERVED,EVAC_49_RESERVED,EVAC_50_RESERVED)
(SELECT TO_DATE(TO_CHAR(SYSDATE, 'MM/DD/YYYY'), 'MM/DD/YYYY'), '$1', EVAC_01_SERIAL_NUMBER,EVAC_02_REGION_ID,EVAC_03_MSISDN_DEALER,EVAC_04_INITIATOR_DEALER_ID,EVAC_05_INITIATOR_TEMPLATE_ID,EVAC_06_DEALER_NAME,EVAC_07_BRAND_TYPE,EVAC_08_USER_BRAND_TYPE,EVAC_09_PRICE,EVAC_10_MSISDN,EVAC_11_SUBSCRIBER_TYPE,EVAC_12_RECHARGE_DATE,EVAC_13_SERIAL_NUMBER_RECHARGEABLE_CARD,EVAC_14_RESPONSE_STATE ,EVAC_15_TRANSACTION_STATUS,EVAC_16_ADJUST_STATUS,EVAC_17_ERROR_MESSAGE,EVAC_18_ACCESS_TYPE,EVAC_19_DEALER_ACTUAL_DECREASE_MONEY,EVAC_20_ACCEPTOR_ACTUAL_INCREASE_MONEY,EVAC_21_COMMISSION_RATE_RECHARGE,EVAC_22_SENDER_ID,EVAC_23_ICCID,EVAC_24_BALANCE_STOCK_ADJUSTOR,EVAC_25_RECHARGE_HANDLING_FEE,EVAC_26_BALANCE_AFTER_RECHARGE,EVAC_27_ENCRYPTED_MSISDN,EVAC_28_CELL_ID,EVAC_29_SOURCE_MESSAGE,EVAC_30_DESTINATION_MESSAGE,EVAC_31_FUNCTION_ID,EVAC_32_ACCOUNT_INDEX,EVAC_33_OLD_BALANCE,EVAC_34_NEW_BALANCE,EVAC_35_NEW_VALIDITY,EVAC_36_RESERVED,EVAC_37_ERROR_CODE,EVAC_38_RECHARGE_DURATION,EVAC_39_IN_RECHARGE_DURATION,EVAC_40_UPSTREAM_MSISDN,EVAC_41_UPSTREAM_NAME,EVAC_42_CELL_ID_RECHARGED_PARTY,EVAC_43_RESERVED,EVAC_44_RESERVED,EVAC_45_RESERVED,EVAC_46_RESERVED,EVAC_47_RESERVED,EVAC_48_RESERVED,EVAC_49_RESERVED,EVAC_50_RESERVED FROM EVCREC_EXT)




/
COMMIT
/
UPDATE cdr_head
   SET process_status=96
 WHERE source='evcREC'
   AND file_name='$1'
/
COMMIT
/
EXIT
EOF
}

# ======= SMSC SECTION =====

lock=/data02/scripts/dwh/lock/evcREC_lock  export lock

if [ -f $lock ] ; then
exit 2

else
touch $lock

fileList=`get_smsc_files`

for fil in $fileList
do

v3=`echo ${fil}|sed s/,/\ /g|awk '{print $3}'`   ### file name
v4=`echo ${fil}|sed s/,/\ /g|awk '{print $4}'`   ### file id

cd /data02/scripts/dwh/file_loader/
sh create_evcREC_ext_tab.sh $v3
createSMSCUpdate $v3
insertSMSCUpdate $v3


# ~~~~~~~~~~~~~~~~~~~~~~~~
updateOnError $v3 $v4
#~~~~~~~~~~~~~~~~~~~~~~~~~

done

rm -f $lock

fi

