PATH=$PATH:$HOME/.local/bin:$HOME/bin

export PATH

export TMP=/tmp
export TMPDIR=$TMP

export ORACLE_HOSTNAME=dwhnode05
export ORACLE_UNQNAME=dwhdb05
export ORACLE_BASE=/data01/app/oracle
export ORACLE_HOME=$ORACLE_BASE/product/19.0.0/dbhome_1
export ORA_INVENTORY=/data01/app/oraInventory
export ORACLE_SID=dwhdb05
export DATA_DIR=/data01/oradata

export PATH=/usr/sbin:/usr/local/bin:$PATH
export PATH=$ORACLE_HOME/bin:$PATH

export LD_LIBRARY_PATH=$ORACLE_HOME/lib:/lib:/usr/lib
export CLASSPATH=$ORACLE_HOME/jlib:$ORACLE_HOME/rdbms/jlib


# This function changes the status of files where errors where encountered to 34
updateOnError()
{
sqlplus  -s <<EOF
dwh_user/dwh_user_123
SET echo off
SET head off
SET feedback off
REM "WHENEVER SQLERROR EXIT SQL.SQLCODE"
UPDATE cdr_head
   SET process_status=34
 WHERE file_name='$1'
   AND process_status=30
/
COMMIT
/
EXIT
EOF
}

# This function lists files after mediation and status is =30

get_smsc_files()
{

sqlplus  -s <<EOF
dwh_user/dwh_user_123
SET head off
SET feedback off
SET pagesize 0
SET verify off
SET linesize 400
SELECT '/data02/card/evcREC/process/'||','||'/data02/card/evcREC/process/'||file_name||','||file_name||','||file_id
  FROM cdr_head
 WHERE source='evcREC'
   AND process_status=30
   and rownum < 1000 
/
EOF
}


createSMSCUpdate()
{
sqlplus  -s <<EOF
dwh_user/dwh_user_123
SET echo on
SET head off
SET feedback off
WHENEVER SQLERROR EXIT SQL.SQLCODE

UPDATE cdr_head
   SET process_status=32
 WHERE source='evcREC'
   AND file_name='$1'
/
COMMIT
/
EXIT
EOF
}

insertSMSCUpdate()
{
sqlplus  -s <<EOF
dwh_user/dwh_user_123
SET echo on
SET head off
SET feedback off
WHENEVER SQLERROR EXIT SQL.SQLCODE

INSERT INTO L1_EVCREC(PROCESSED_DATE,FILE_NAME,ER01_SERIAL_NUMBER,ER02_REGION_ID,ER03_MSISDN_DEALER,ER04_INITIATOR_DEALER_ID,ER05_INITIATOR_TEMPLATE_ID,ER06_DEALER_NAME,ER07_BRAND_TYPE,ER08_USER_BRAND_TYPE,ER09_PRICE,ER10_MSISDN,ER11_SUBSCRIBER_TYPE,ER12_RECHARGE_DATE,ER13_SERIAL_NUMBER_CARD,ER14_RESPONSE_STATE,ER15_TRANSACTION_STATUS,ER16_ADJUST_STATUS,ER17_ERROR_MESSAGE,ER18_ACCESS_TYPE,ER19_DEALER_DECREASE_MONEY,ER20_ACCEPTOR_INCREASE_MONEY,ER21_COMMISSION_RATE_RECHARGE,ER22_SENDER_ID,ER23_ICCID,ER24_BALANCE_STOCK_ADJUSTOR,ER25_RECHARGE_HANDLING_FEE,ER26_BALANCE_AFTER_RECHARGE,ER27_ENCRYPTED_MSISDN,ER28_CELL_ID,ER29_SOURCE_MESSAGE,ER30_DESTINATION_MESSAGE,ER31_FUNCTION_ID,ER32_ACCOUNT_INDEX,ER33_OLD_BALANCE,ER34_NEW_BALANCE,ER35_NEW_VALIDITY,ER36_RESERVED,ER37_ERROR_CODE,ER38_RECHARGE_DURATION,ER39_IN_RECHARGE_DURATION,ER40_UPSTREAM_MSISDN,ER41_UPSTREAM_NAME,ER42_CELL_ID_RECHARGED_PARTY,ER43_RESERVED,ER44_RESERVED,ER45_RESERVED,ER46_RESERVED,ER47_RESERVED,ER48_RESERVED,ER49_RESERVED,ER50_RESERVED)
(SELECT TO_DATE(TO_CHAR(SYSDATE, 'MM/DD/YYYY'), 'MM/DD/YYYY')as PROCESSED_DATE,'$1',ER01_SERIAL_NUMBER,ER02_REGION_ID,ER03_MSISDN_DEALER,ER04_INITIATOR_DEALER_ID,ER05_INITIATOR_TEMPLATE_ID,ER06_DEALER_NAME,ER07_BRAND_TYPE,ER08_USER_BRAND_TYPE,ER09_PRICE,ER10_MSISDN,ER11_SUBSCRIBER_TYPE,ER12_RECHARGE_DATE,ER13_SERIAL_NUMBER_CARD,ER14_RESPONSE_STATE,ER15_TRANSACTION_STATUS,ER16_ADJUST_STATUS,ER17_ERROR_MESSAGE,ER18_ACCESS_TYPE,ER19_DEALER_DECREASE_MONEY,ER20_ACCEPTOR_INCREASE_MONEY,ER21_COMMISSION_RATE_RECHARGE,ER22_SENDER_ID,ER23_ICCID,ER24_BALANCE_STOCK_ADJUSTOR,ER25_RECHARGE_HANDLING_FEE,ER26_BALANCE_AFTER_RECHARGE,ER27_ENCRYPTED_MSISDN,ER28_CELL_ID,ER29_SOURCE_MESSAGE,ER30_DESTINATION_MESSAGE,ER31_FUNCTION_ID,ER32_ACCOUNT_INDEX,ER33_OLD_BALANCE,ER34_NEW_BALANCE,ER35_NEW_VALIDITY,ER36_RESERVED,ER37_ERROR_CODE,ER38_RECHARGE_DURATION,ER39_IN_RECHARGE_DURATION,ER40_UPSTREAM_MSISDN,ER41_UPSTREAM_NAME,ER42_CELL_ID_RECHARGED_PARTY,ER43_RESERVED,ER44_RESERVED,ER45_RESERVED,ER46_RESERVED,ER47_RESERVED,ER48_RESERVED,ER49_RESERVED,ER50_RESERVED FROM EVCREC_EXT)
/
COMMIT
/
UPDATE cdr_head
   SET process_status=96
 WHERE source='evcREC'
   AND file_name='$1'
/
COMMIT
/
EXIT
EOF
}

# ======= SMSC SECTION =====

lock=/data02/scripts/dwh/lock/evcREC_lock  export lock

if [ -f $lock ] ; then
exit 2

else
touch $lock

fileList=`get_smsc_files`

for fil in $fileList
do

v3=`echo ${fil}|sed s/,/\ /g|awk '{print $3}'`   ### file name
v4=`echo ${fil}|sed s/,/\ /g|awk '{print $4}'`   ### file id

cd /data02/scripts/dwh/file_loader/
sh create_evcREC_ext_tab.sh $v3
createSMSCUpdate $v3
insertSMSCUpdate $v3


# ~~~~~~~~~~~~~~~~~~~~~~~~
updateOnError $v3 $v4
#~~~~~~~~~~~~~~~~~~~~~~~~~

done

rm -f $lock

fi

