--
-- L1_HUAWEIUDN_API  (View) 
--
CREATE OR REPLACE FORCE VIEW DWH_USER.L1_HUAWEIUDN_API
(PROCESSED_DATE, STARTTIME, ENDTIME, MS_IP, MS_PORT, 
 SERVER_IP, SERVER_PORT, MSISDN, IMSI, IMEISV, 
 CGI, SAI, ECGI)
BEQUEATH DEFINER
AS 
SELECT PROCESSED_DATE,
          IP1_STARTTIME,
          IP2_ENDTIME,
          IP3_MS_IP,
          IP4_MS_PORT,
          IP5_SERVER_IP,
          IP6_SERVER_PORT,
          IP7_MSISDN,
          IP8_IMSI,
          IP9_IMEI,
          IP10_CGI,
          IP11_SAI,
          IP12_ECGI
     FROM L1_HUAWEIUDN;


