--
-- P_L1_TO_L2_CONTENT_MANUAL  (Procedure) 
--
CREATE OR REPLACE PROCEDURE DWH_USER.P_L1_TO_L2_CONTENT_MANUAL (P_PROCESS_DATE VARCHAR2) IS
    VCOUNT NUMBER;
    VDATE_KEY NUMBER;
    VSTATUS NUMBER;
    VDATE DATE := TO_DATE(TO_DATE(P_PROCESS_DATE,'YYYYMMDD'),'DD/MM/RRRR');
BEGIN
        INSERT INTO L2_CONTENT
        SELECT /*+ PARALLEL(O,16) */
        C.DATE_KEY AS ETL_DATE_KEY,
        O.FILE_NAME, 
        CO4_SPLIT_CDR_REASON, 
        CO9_STATUS, 
        CO18_OBJ_TYPE, 
        CO22_PRI_IDENTITY, 
        CO24_SERVICE_CATEGORY, 
        CO25_USAGE_SERVICE_TYPE, 
        NVL(CO41_DEBIT_AMOUNT,0) / 1000000 AS CO41_DEBIT_AMOUNT,
        CO372_CALLINGPARTYNUMBER, 
        CO373_CALLINGPARTYIMSI, 
        CO374_CHARGINGTYPE, 
        CO375_CHARGINGUSAGETYPE, 
        CO382_SERVICETYPE, 
        CO383_CONTENTTYPE, 
        CO384_SERVICECAPABILITY, 
        CO385_PROVISIONTYPE, 
        CO386_CATEGORYTYPE, 
        CO388_TIMES, 
        CO389_DURATION, 
        CO396_MAINOFFERINGID, 
        B.DATE_KEY AS CO402_STARTTIMEOFBILLCYL_KEY, 
        TO_CHAR(TO_DATE( SUBSTR(CO402_STARTTIMEOFBILLCYCLE,9,4), 'HH24MI')+360/1440, 'HH24MI') AS CO402_STARTTIMEOFBILLCYL_HOUR,--SUBSTR(CO402_STARTTIMEOFBILLCYCLE,9,4) AS CO402_STARTTIMEOFBILLCYL_HOUR,
        CO405_MAINBALANCEINFO, 
        CO406_CHGBALANCEINFO, 
        CO407_CHGFREEUNITINFO, 
        CO410_PAYTYPE, 
        NVL(CO431_PREPAID_BALANCE,0) / 1000000 AS CO431_PREPAID_BALANCE,
        NVL(CO432_POSTPAID_BALANCE,0) / 1000000 AS CO432_POSTPAID_BALANCE
        FROM  L1_CONTENT O,DATE_DIM B,DATE_DIM C  
        WHERE TO_CHAR(B.DATE_VALUE,'YYYYMMDD')=TO_CHAR(TO_DATE( SUBSTR(O.CO402_STARTTIMEOFBILLCYCLE,1,12), 'YYYYMMDDHH24MI')+6/24, 'YYYYMMDD')--WHERE TO_DATE(B.DATE_VALUE,'DD/MM/YYYY')=TO_DATE(TO_DATE( SUBSTR(O.CO402_STARTTIMEOFBILLCYCLE,1,8), 'YYYYMMDD'), 'DD/MM/YYYY')
        AND TO_DATE(C.DATE_VALUE,'DD/MM/YYYY')=TO_DATE(O.PROCESSED_DATE, 'DD/MM/YYYY')
        AND TO_CHAR(O.PROCESSED_DATE,'YYYYMMDD') = '20200602';
        COMMIT;
        INSERT INTO ETL_LOG (LAYER, DATE_KEY, SOURCE, STATUS, FILE_COUNT, PER_COUNT, POST_COUNT, INSERT_TIME)
        VALUES              ('L2_CONTENT',VDATE_KEY,'com','30',VCOUNT,'','',SYSDATE);
        COMMIT;
EXCEPTION
 WHEN OTHERS THEN NULL;
END;
/

