--
-- P_L1_ETSAF  (Procedure) 
--
CREATE OR REPLACE PROCEDURE DWH_USER.P_L1_ETSAF (P_PROCESS_DATE VARCHAR2) IS
    VDATE DATE := TO_DATE(TO_DATE(P_PROCESS_DATE,'YYYYMMDD'),'DD/MM/RRRR');
BEGIN

INSERT INTO L1_ETSAF
SELECT /*+ parallel (A,16)*/
TRUNC(VDATE),
SAF_ID,
SAF_MSISDN,
SAF_NID,
SAF_SUBSCRIBERNAME,
SAF_DOB,
SAF_GENDER,
SAF_DIVISIONID,
SAF_DISTRICTID,
SAF_THANAID,
SAF_ADDRESS,
SAF_PHOTONID,
SAF_PHOTOSAF,
SAF_PHOTOUSR,
SAF_DEALERMOBILE,
SAF_REGTYPE,
SAF_REGDONEBY,
SAF_DEALERID,
SAF_RETAILERMOBILE,
SAF_SALESMAN,
SAF_SALEDATE,
SAF_VERIFIED,
SAF_ENTRYDATE,
SAF_IPADDRESS,
SAF_EXTFLD,
SAF_TXN,
SAF_IDENTIFIER,
SAF_PKG,
SAF_ICCID,
SAF_EXP_DATE,
SAF_CAMPAIGN_MSISDN,
SAF_CORPORATE,
SAF_CAMPAIGN,
SAF_REG_TYPE_DESC,
SAF_ERR_CODE,
SAF_ERR_DTLS,
SAF_CAMPAIGN_OTP
FROM ASDBVS.TBL_SAF@DWH01TOETSAF A
WHERE TRUNC(A.SAF_ENTRYDATE)=TRUNC(VDATE);
COMMIT;
END;
/

