--
-- P_L1_TO_L2_MANAGEMENT_MANUAL_ETL  (Procedure) 
--
CREATE OR REPLACE PROCEDURE DWH_USER.P_L1_TO_L2_MANAGEMENT_MANUAL_ETL (P_PROCESS_DATE VARCHAR2) IS
    VCOUNT NUMBER;
    VDATE_KEY NUMBER;
    VSTATUS NUMBER;
    VSTATUS2 NUMBER;
    VDATE DATE := TO_DATE(TO_DATE(P_PROCESS_DATE,'YYYYMMDD'),'DD/MM/RRRR');
BEGIN
    SELECT COUNT(*) INTO VCOUNT 
    FROM CDR_HEAD_MERGE
    WHERE SOURCE = 'cm'
    AND PROCESS_STATUS = 96
    AND TO_DATE(PROCESS_DATE,'DD/MM/RRRR') = VDATE;
    
    SELECT DATE_KEY INTO VDATE_KEY FROM DATE_DIM
    WHERE DATE_KEY = (SELECT A.DATE_KEY FROM DATE_DIM A WHERE A.DATE_VALUE = VDATE-1);
    
  IF VCOUNT >= 1  THEN
      INSERT INTO ETL_LOG (LAYER, DATE_KEY, SOURCE, STATUS, FILE_COUNT, PER_COUNT, POST_COUNT, INSERT_TIME)
      VALUES              ('L1_MANAGEMENT',VDATE_KEY,'cm','96',VCOUNT,'','',SYSDATE);
        
    SELECT STATUS INTO VSTATUS
    FROM ETL_LOG
    WHERE DATE_KEY = (SELECT A.DATE_KEY FROM DATE_DIM A WHERE A.DATE_VALUE = VDATE-2)
    AND LAYER = 'L2_MANAGEMENT'
    AND SOURCE = 'cm';
    
    
    SELECT COUNT(STATUS) INTO VSTATUS2
    FROM ETL_LOG
    WHERE DATE_KEY = (SELECT A.DATE_KEY FROM DATE_DIM A WHERE A.DATE_VALUE = VDATE-1)
    AND LAYER = 'L2_MANAGEMENT'
    AND SOURCE = 'cm';   
       
    
    IF VSTATUS = 96 AND VSTATUS2 = 0 THEN
        INSERT INTO ETL_LOG (LAYER, DATE_KEY, SOURCE, STATUS, FILE_COUNT, PER_COUNT, POST_COUNT, INSERT_TIME)
        VALUES              ('L2_MANAGEMENT',VDATE_KEY,'cm','30',VCOUNT,'','',SYSDATE);

        INSERT INTO L2_MANAGEMENT
        SELECT /*+ PARALLEL(M,8) */
        C.DATE_KEY-1 AS ETL_DATE_KEY,
        M.FILE_NAME, 
        M4_SPLIT_CDR_REASON,
        M9_STATUS, 
        M18_OBJ_TYPE, 
        M22_PRI_IDENTITY, 
        M24_SERVICE_CATEGORY, 
        M25_USAGE_SERVICE_TYPE, 
        NVL(M41_DEBIT_AMOUNT,0) / 1000000 AS M41_DEBIT_AMOUNT,
        M372_CALLINGPARTYNUMBER, 
        M374_OPERATIONTYPE, 
        M376_MAINOFFERINGID, 
        M377_PAYTYPE, 
        B.DATE_KEY AS M378_STARTTIMEOFBILLCYL_KEY, 
        TO_CHAR(TO_DATE( SUBSTR(M378_STARTTIMEOFBILLCYCLE,9,4), 'HH24MI')+360/1440, 'HH24MI') AS  M378_STARTTIMEOFBILLCYL_HOUR,--SUBSTR(M378_STARTTIMEOFBILLCYCLE,9,4) AS M378_STARTTIMEOFBILLCYL_HOUR, 
        M385_USERSTATE, 
        M399_CHARGEPARTYINDICATOR, 
        M401_TAXINFO, 
        NVL(M402_PREPAID_BALANCE,0) / 1000000 AS  M402_PREPAID_BALANCE,
        NVL(M403_POSTPAID_BALANCE,0) / 1000000 AS M403_POSTPAID_BALANCE 
        FROM  L1_MANAGEMENT M,DATE_DIM B,DATE_DIM C
        WHERE TO_CHAR(B.DATE_VALUE,'YYYYMMDD')=TO_CHAR(TO_DATE( SUBSTR(M.M378_STARTTIMEOFBILLCYCLE,1,12), 'YYYYMMDDHH24MI')+6/24, 'YYYYMMDD')--WHERE TO_DATE(B.DATE_VALUE,'DD/MM/YYYY')=TO_DATE(TO_DATE( SUBSTR(M.M378_STARTTIMEOFBILLCYCLE,1,8), 'yyyymmdd'), 'DD/MM/YYYY')
        AND TO_DATE(C.DATE_VALUE,'DD/MM/YYYY')=TO_DATE(M.PROCESSED_DATE, 'DD/MM/YYYY')
        AND TO_DATE(M.PROCESSED_DATE,'DD/MM/RRRR') = VDATE;
        COMMIT;
    UPDATE ETL_LOG SET STATUS = 96 
    WHERE DATE_KEY = VDATE_KEY
    AND LAYER = 'L2_MANAGEMENT';        
        COMMIT;
    END IF;
  ELSE
    INSERT INTO ETL_LOG (LAYER, DATE_KEY, SOURCE, STATUS, FILE_COUNT, PER_COUNT, POST_COUNT, INSERT_TIME)
    VALUES              ('L2_MANAGEMENT',VDATE_KEY,'cm','33',VCOUNT,'','',SYSDATE);
    COMMIT;
  END IF;
EXCEPTION
 WHEN OTHERS THEN NULL;
END;
/

