--
-- P_L1_TO_L2_VOICE_MANUAL_ETL  (Procedure) 
--
CREATE OR REPLACE PROCEDURE DWH_USER.P_L1_TO_L2_VOICE_MANUAL_ETL (P_PROCESS_DATE VARCHAR2) IS
    VCOUNT NUMBER;
    VDATE_KEY NUMBER;
    VSTATUS NUMBER;
    VSTATUS2 NUMBER;
    VDATE DATE := TO_DATE(TO_DATE(P_PROCESS_DATE,'YYYYMMDD'),'DD/MM/RRRR');
BEGIN
    SELECT COUNT(*) INTO VCOUNT 
    FROM CDR_HEAD_MERGE
    WHERE SOURCE = 'voice'
    AND PROCESS_STATUS = 96
    AND TO_DATE(PROCESS_DATE,'DD/MM/RRRR') = VDATE;
    
    SELECT DATE_KEY INTO VDATE_KEY FROM DATE_DIM
    WHERE DATE_KEY = (SELECT A.DATE_KEY FROM DATE_DIM A WHERE A.DATE_VALUE = VDATE-1);
    
    
  IF VCOUNT >= 1  THEN
      INSERT INTO ETL_LOG (LAYER, DATE_KEY, SOURCE, STATUS, FILE_COUNT, PER_COUNT, POST_COUNT, INSERT_TIME)
    VALUES              ('L1_VOICE',VDATE_KEY,'voice','96',VCOUNT,'','',SYSDATE);
        
    SELECT STATUS INTO VSTATUS
    FROM ETL_LOG
    WHERE DATE_KEY = (SELECT A.DATE_KEY FROM DATE_DIM A WHERE A.DATE_VALUE = VDATE-2)
    AND LAYER = 'L2_VOICE'
    AND SOURCE = 'voice';

    SELECT COUNT(STATUS) INTO VSTATUS2
    FROM ETL_LOG
    WHERE DATE_KEY = (SELECT A.DATE_KEY FROM DATE_DIM A WHERE A.DATE_VALUE = VDATE-1)
    AND LAYER = 'L2_VOICE'
    AND SOURCE = 'voice';    
    
    IF VSTATUS = 96 AND VSTATUS2=0 THEN
        INSERT INTO ETL_LOG (LAYER, DATE_KEY, SOURCE, STATUS, FILE_COUNT, PER_COUNT, POST_COUNT, INSERT_TIME)
        VALUES              ('L2_VOICE',VDATE_KEY,'voice','30',VCOUNT,'','',SYSDATE);

        INSERT INTO L2_VOICE
        SELECT /*+ PARALLEL(V,8) */
        C.DATE_KEY-1 AS ETL_DATE_KEY,
        v.FILE_NAME,
        V24_SERVICE_CATEGORY            ,
        V25_USAGE_SERVICE_TYPE          ,
        V35_RATE_USAGE                  ,
        V36_SERVICE_UNIT_TYPE           ,
        NVL(V41_DEBIT_AMOUNT,0) / 1000000 AS V41_DEBIT_AMOUNT,
        NVL(V44_DEBIT_FROM_ADVANCE_PRE,0) / 1000000 AS V44_DEBIT_FROM_ADVANCE_PRE,
        V49_PAY_FREE_UNIT_TIMES         ,
        V50_PAY_FREE_UNIT_DURATION      ,
        NVL(V55_CUR_BALANCE,0) / 1000000 AS V55_CUR_BALANCE,
        V372_CALLINGPARTYNUMBER         ,
        V373_CALLEDPARTYNUMBER          ,
        V378_SERVICEFLOW                ,
        V380_CALLINGROAMINFO            ,
        V381_CALLINGCELLID              ,
        V383_CALLEDCELLID       ,        
        V386_BEARERCAPABILITY           ,
        B.DATE_KEY AS V387_CHARGINGTIME_KEY           , -- convert to key
        TO_CHAR(TO_DATE( SUBSTR(V387_CHARGINGTIME,9,4), 'HH24MI')+360/1440, 'HH24MI') AS  V387_CHARGINGTIME_HOUR,--SUBSTR(V387_CHARGINGTIME,9,4) AS  V387_CHARGINGTIME_HOUR ,-- NEW
        V389_TERMINATIONREASON          ,
        V391_IMEI                       ,
        V394_REDIRECTINGPARTYID         ,
        V395_MSCADDRESS                 ,
        V397_MAINOFFERINGID             ,
        V400_PAYTYPE                    ,
        V403_ROAMSTATE                  ,
        V405_CALLINGHOMEAREANUMBER      ,
        V417_HOTLINEINDICATOR,
        V425_CALLINGNETWORKTYPE         ,
        V434_ONLINECHARGINGFLAG         ,
        V457_PREPAID_BALANCE / 1000000 as   V457_PREPAID_BALANCE,
        V476_ONNETINDICATOR  ,
        V402_CALLTYPE  ,
        V436_LASTEFFECTOFFERING         
        FROM  L1_VOICE V,DATE_DIM B,DATE_DIM C
        WHERE TO_CHAR(B.DATE_VALUE,'YYYYMMDD')=TO_CHAR(TO_DATE( SUBSTR(V.V387_CHARGINGTIME,1,12), 'YYYYMMDDHH24MI')+6/24, 'YYYYMMDD')--WHERE TO_DATE(B.DATE_VALUE,'DD/MM/YYYY')=TO_DATE(TO_DATE( SUBSTR(V.V387_CHARGINGTIME,1,8), 'YYYYMMDD'), 'DD/MM/YYYY')
        AND TO_DATE(C.DATE_VALUE,'DD/MM/YYYY')=TO_DATE(V.PROCESSED_DATE, 'DD/MM/YYYY')
        AND TO_DATE(V.PROCESSED_DATE,'DD/MM/RRRR') = VDATE;
        COMMIT;
    UPDATE ETL_LOG SET STATUS = 96 
    WHERE DATE_KEY = VDATE_KEY
    AND LAYER = 'L2_VOICE';        
        COMMIT;
    END IF;
  ELSE
        INSERT INTO ETL_LOG (LAYER, DATE_KEY, SOURCE, STATUS, FILE_COUNT, PER_COUNT, POST_COUNT, INSERT_TIME)
        VALUES              ('L2_VOICE',VDATE_KEY,'voice','34',VCOUNT,'','',SYSDATE);
    COMMIT;
  END IF;
EXCEPTION
 WHEN OTHERS THEN NULL;
END;
/

