--
-- P_L1_TO_L2_MANAGEMENT_MANUAL  (Procedure) 
--
CREATE OR REPLACE PROCEDURE DWH_USER.P_L1_TO_L2_MANAGEMENT_MANUAL (P_PROCESS_DATE VARCHAR2) IS
    VCOUNT NUMBER;
    VDATE_KEY NUMBER;
    VSTATUS NUMBER;
    VDATE DATE := TO_DATE(TO_DATE(P_PROCESS_DATE,'YYYYMMDD'),'DD/MM/RRRR');
BEGIN
        INSERT INTO L2_MANAGEMENT
        SELECT /*+ PARALLEL(M,16) */
        C.DATE_KEY AS ETL_DATE_KEY,
        M.FILE_NAME, 
        M4_SPLIT_CDR_REASON,
        M9_STATUS, 
        M18_OBJ_TYPE, 
        M22_PRI_IDENTITY, 
        M24_SERVICE_CATEGORY, 
        M25_USAGE_SERVICE_TYPE, 
        NVL(M41_DEBIT_AMOUNT,0) / 1000000 AS M41_DEBIT_AMOUNT,
        M372_CALLINGPARTYNUMBER, 
        M374_OPERATIONTYPE, 
        M376_MAINOFFERINGID, 
        M377_PAYTYPE, 
        B.DATE_KEY AS M378_STARTTIMEOFBILLCYL_KEY, 
        TO_CHAR(TO_DATE( SUBSTR(M378_STARTTIMEOFBILLCYCLE,9,4), 'HH24MI')+360/1440, 'HH24MI') AS  M378_STARTTIMEOFBILLCYL_HOUR,--SUBSTR(M378_STARTTIMEOFBILLCYCLE,9,4) AS M378_STARTTIMEOFBILLCYL_HOUR, 
        M385_USERSTATE, 
        M399_CHARGEPARTYINDICATOR, 
        M401_TAXINFO, 
        NVL(M402_PREPAID_BALANCE,0) / 1000000 AS  M402_PREPAID_BALANCE,
        NVL(M403_POSTPAID_BALANCE,0) / 1000000 AS M403_POSTPAID_BALANCE 
        FROM  L1_MANAGEMENT M,DATE_DIM B,DATE_DIM C
        WHERE TO_CHAR(B.DATE_VALUE,'YYYYMMDD')=TO_CHAR(TO_DATE( SUBSTR(M.M378_STARTTIMEOFBILLCYCLE,1,12), 'YYYYMMDDHH24MI')+6/24, 'YYYYMMDD')--WHERE TO_DATE(B.DATE_VALUE,'DD/MM/YYYY')=TO_DATE(TO_DATE( SUBSTR(M.M378_STARTTIMEOFBILLCYCLE,1,8), 'yyyymmdd'), 'DD/MM/YYYY')
        AND TO_DATE(C.DATE_VALUE,'DD/MM/YYYY')=TO_DATE(M.PROCESSED_DATE, 'DD/MM/YYYY')
        AND TO_CHAR(M.PROCESSED_DATE,'YYYYMMDD') = P_PROCESS_DATE;
        COMMIT;
        INSERT INTO ETL_LOG (LAYER, DATE_KEY, SOURCE, STATUS, FILE_COUNT, PER_COUNT, POST_COUNT, INSERT_TIME)
        VALUES              ('L2_MANAGEMENT',VDATE_KEY,'cm','96',VCOUNT,'','',SYSDATE);
        COMMIT;
EXCEPTION
 WHEN OTHERS THEN NULL;
END;
/

