--
-- P_L1_TO_L2_DATA_MANUAL3  (Procedure) 
--
CREATE OR REPLACE PROCEDURE DWH_USER.P_L1_TO_L2_DATA_MANUAL3(P_PROCESS_DATE VARCHAR2) IS
    VCOUNT NUMBER;
    VDATE_KEY NUMBER;
    VSTATUS NUMBER;
    VDATE DATE := TO_DATE(TO_DATE(P_PROCESS_DATE,'YYYYMMDD'),'DD/MM/RRRR');--TO_CHAR(TO_DATE(P_PROCESS_DATE,'RRRRMMDD'), 'DD/

BEGIN
        INSERT INTO L2_DATA
        SELECT /*+ PARALLEL(A,16) */
        C.DATE_KEY AS ETL_DATE_KEY,
        A.FILE_NAME,
        NVL(G41_DEBIT_AMOUNT,0) / 1000000 ,
        G51_FREE_UNIT_AMOUNT_OF_FLUX,
        G372_CALLINGPARTYNUMBER     ,
        G375_CALLINGPARTYIMSI       ,
        G379_CALLINGCELLID              ,
        B.DATE_KEY AS  G383_CHARGINGTIME_KEY       ,
        TO_CHAR(TO_DATE( SUBSTR(G383_CHARGINGTIME,9,4), 'HH24MI')+360/1440, 'HH24MI') AS  G383_CHARGINGTIME_HOUR,--SUBSTR(G383_CHARGINGTIME,9,4) AS  G383_CHARGINGTIME_HOUR     ,
        G384_TOTALFLUX                            ,
        G388_IMEI                                 ,
        G389_SERVICEID                            ,
        G401_MAINOFFERINGID                       ,
        G403_PAYTYPE                              ,
        G404_CHARGINGTYPE                         ,
        G412_SERVICETYPE                          ,
        G418_LASTEFFECTOFFERING                   ,
        G429_RATTYPE                              ,
        G430_CHARGEPARTYINDICATOR                 ,
        NVL(G432_PRIMARYOFFERCHGAMT,0) / 1000000  ,
        G435_TAXINFO                              ,
        G446_PAY_FREE_UNIT_FLUX                   ,
        G447_PAY_FREE_UNIT_DURATION               ,
        NVL(G448_PAY_DEBIT_AMOUNT,0) / 1000000    ,
        NVL(G449_PAY_DEBIT_FROM_PREPAID,0) / 1000000 ,
        NVL(G450_PAY_PREPAID_BALANCE,0) / 1000000 ,
        NVL(G453_PAY_POSTPAID_BALANCE,0) / 1000000,
        G455_SUBSCRIBERIDTYPE                     ,
        G467_ACCUMLATEDPOINT
        FROM  L1_DATA A,DATE_DIM B,DATE_DIM C
        WHERE TO_CHAR(B.DATE_VALUE,'YYYYMMDD')=TO_CHAR(TO_DATE( SUBSTR(A.G383_CHARGINGTIME,1,12), 'YYYYMMDDHH24MI')+6/24, 'YYYYMMDD')--WHERE TO_DATE(B.DATE_VALUE,'DD/MM/YYYY')=TO_DATE(TO_DATE( SUBSTR(A.G383_CHARGINGTIME,1,8), 'YYYYMMDD'), 'DD/MM/YYYY')
        AND TO_DATE(C.DATE_VALUE,'DD/MM/YYYY')=TO_DATE(A.PROCESSED_DATE, 'DD/MM/YYYY')
        AND TO_CHAR(A.PROCESSED_DATE,'YYYYMMDD') = P_PROCESS_DATE;
        COMMIT;
        INSERT INTO ETL_LOG (LAYER, DATE_KEY, SOURCE, STATUS, FILE_COUNT, PER_COUNT, POST_COUNT, INSERT_TIME)
        VALUES              ('L2_DATA',VDATE_KEY,'data','96',VCOUNT,'','',SYSDATE);
        COMMIT;
        EXCEPTION
WHEN OTHERS THEN NULL;
END;
/

