--
-- P_TEST_SUB_IDEN_101  (Procedure) 
--
CREATE OR REPLACE PROCEDURE DWH_USER.P_TEST_SUB_IDEN_101 (P_PROCESS_DATE VARCHAR2) IS
    VDATE DATE := TO_DATE(TO_DATE(P_PROCESS_DATE,'YYYYMMDD'),'DD/MM/RRRR');
BEGIN

INSERT INTO TEST_SUB_IDEN_101(PROCESSED_DATE,SUB_ID, MSISDN,EVENT_DATE)
SELECT TRUNC(VDATE)VDATE,COLUMN1, COLUMN2,P_PROCESS_DATE
FROM TEST_SUB_IDEN_101_EXT;
COMMIT;

EXCEPTION
 WHEN OTHERS THEN NULL;
END;
/

