--
-- P_TEST_BC_OFFERING_INST_101  (Procedure) 
--
CREATE OR REPLACE PROCEDURE DWH_USER.P_TEST_BC_OFFERING_INST_101 (P_PROCESS_DATE VARCHAR2) IS
    VDATE DATE := TO_DATE(TO_DATE(P_PROCESS_DATE,'YYYYMMDD'),'DD/MM/RRRR');
BEGIN
  INSERT INTO TEST_BC_OFFERING_INST_101(PROCESSED_DATE,SUB_ID, TYPE, OFFERID, EFF_DATE, EXP_DATE,EVENT_DATE)
SELECT TRUNC(VDATE)VDATE,COLUMN1, COLUMN2, COLUMN3, COLUMN4, COLUMN5,P_PROCESS_DATE
FROM TEST_BC_OFFERING_INST_101_EXT;
COMMIT;
EXCEPTION
 WHEN OTHERS THEN NULL;
END;
/

