--
-- SP_ERP_ETL  (Procedure) 
--
CREATE OR REPLACE PROCEDURE DWH_USER.SP_ERP_ETL AS
VDATE_KEY           VARCHAR2(4);
VHR_BU_ERP          NUMBER :=0;
VIN_ITEM_ERP        NUMBER :=0;
VSL_CUSTOMER_ERP    NUMBER :=0;
VSL_CUSTTYPE_ERP    NUMBER :=0;
VSL_INVOICEDTL_ERP  NUMBER :=0;
VSL_INVOICE_ERP     NUMBER :=0;
----------------------------------
VBU_ERP             NUMBER :=0;
VITEM_ERP           NUMBER :=0;
VCUSTOMER_ERP       NUMBER :=0;
VCUSTTYPE_ERP       NUMBER :=0;
VINVOICEDTL_ERP     NUMBER :=0;
VINVOICE_ERP        NUMBER :=0;

BEGIN

    SELECT DATE_KEY INTO VDATE_KEY 
    FROM DATE_DIM
    WHERE DATE_KEY = (SELECT DATE_KEY FROM DATE_DIM WHERE TRUNC(DATE_VALUE) =TRUNC(SYSDATE-1));
    
    -----------------SYNM_BI_ACCESS_HR_BU_V--------------------

    SELECT COUNT(STATUS) INTO VBU_ERP
    FROM ETL_LOG
    WHERE DATE_KEY = VDATE_KEY
    AND LAYER = 'L1_HR_BU_ERP'
    AND SOURCE = 'ERP';


    SELECT COUNT(*) INTO VHR_BU_ERP
    FROM BMS.SYNM_BI_ACCESS_HR_BU_V@DWH01TOERP
    WHERE  NVL(SS_MODIFIED_ON,0) NOT IN (SELECT NVL(SS_MODIFIED_ON,0)
    FROM L1_HR_BU_ERP)
    OR NVL(SS_CREATED_ON,0) NOT IN (SELECT NVL(SS_CREATED_ON,0) FROM L1_HR_BU_ERP);

    IF VBU_ERP = 0 THEN
        INSERT INTO ETL_LOG (LAYER, DATE_KEY, SOURCE, STATUS, FILE_COUNT, PER_COUNT, POST_COUNT, INSERT_TIME)
        VALUES              ('L1_HR_BU_ERP',VDATE_KEY,'ERP','30',VHR_BU_ERP,'','',SYSDATE);
        COMMIT;

        INSERT INTO L1_HR_BU_ERP
        SELECT *
        FROM BMS.SYNM_BI_ACCESS_HR_BU_V@DWH01TOERP
        WHERE  NVL(SS_MODIFIED_ON,0) NOT IN (SELECT NVL(SS_MODIFIED_ON,0)
        FROM L1_HR_BU_ERP)
        OR NVL(SS_CREATED_ON,0) NOT IN (SELECT NVL(SS_CREATED_ON,0) FROM L1_HR_BU_ERP);
        COMMIT;
        
        UPDATE ETL_LOG SET STATUS = 96,
        UPDATE_TIME=SYSDATE
        WHERE DATE_KEY = VDATE_KEY
        AND LAYER = 'L1_HR_BU_ERP';        
        COMMIT;
    ELSE
        INSERT INTO ETL_LOG (LAYER, DATE_KEY, SOURCE, STATUS, FILE_COUNT, PER_COUNT, POST_COUNT, INSERT_TIME)
        VALUES              ('L1_HR_BU_ERP',VDATE_KEY,'ERP','34',VHR_BU_ERP,'','',SYSDATE);
        COMMIT;
    END IF;
--------------------------SYNM_BI_ACCESS_IN_ITEM_V-------------------------------
    SELECT COUNT(STATUS) INTO VITEM_ERP
    FROM ETL_LOG
    WHERE DATE_KEY = VDATE_KEY
    AND LAYER = 'L1_IN_ITEM_ERP'
    AND SOURCE = 'ERP';
    
    SELECT COUNT(*) INTO VIN_ITEM_ERP
    FROM BMS.SYNM_BI_ACCESS_IN_ITEM_V@DWH01TOERP
    WHERE NVL(SS_MODIFIED_ON,0) NOT IN (SELECT NVL(SS_MODIFIED_ON,0) FROM L1_IN_ITEM_ERP)
    OR NVL(SS_CREATED_ON,0) NOT IN (SELECT NVL(SS_CREATED_ON,0) FROM L1_IN_ITEM_ERP);

    IF VITEM_ERP = 0 THEN
        INSERT INTO ETL_LOG (LAYER, DATE_KEY, SOURCE, STATUS, FILE_COUNT, PER_COUNT, POST_COUNT, INSERT_TIME)
        VALUES              ('L1_IN_ITEM_ERP',VDATE_KEY,'ERP','30',VIN_ITEM_ERP,'','',SYSDATE);
        COMMIT;

        INSERT INTO L1_IN_ITEM_ERP
        SELECT * 
        FROM BMS.SYNM_BI_ACCESS_IN_ITEM_V@DWH01TOERP
        WHERE NVL(SS_MODIFIED_ON,0) NOT IN (SELECT NVL(SS_MODIFIED_ON,0) FROM L1_IN_ITEM_ERP)
        OR NVL(SS_CREATED_ON,0) NOT IN (SELECT NVL(SS_CREATED_ON,0) FROM L1_IN_ITEM_ERP);
        
        UPDATE ETL_LOG SET STATUS = 96,
        UPDATE_TIME=SYSDATE
        WHERE DATE_KEY = VDATE_KEY
        AND LAYER = 'L1_IN_ITEM_ERP';        
        COMMIT;
    ELSE
        INSERT INTO ETL_LOG (LAYER, DATE_KEY, SOURCE, STATUS, FILE_COUNT, PER_COUNT, POST_COUNT, INSERT_TIME)
        VALUES              ('L1_IN_ITEM_ERP',VDATE_KEY,'ERP','34',VIN_ITEM_ERP,'','',SYSDATE);
        COMMIT;
    END IF;
-----------------------SYNM_BI_ACCESS_SL_CUSTOMER_V---------------------------
    SELECT COUNT(STATUS) INTO VCUSTOMER_ERP
    FROM ETL_LOG
    WHERE DATE_KEY = VDATE_KEY
    AND LAYER = 'L1_SL_CUSTOMER_ERP'
    AND SOURCE = 'ERP';


    SELECT COUNT(*) INTO VSL_CUSTOMER_ERP
    FROM BMS.SYNM_BI_ACCESS_SL_CUSTOMER_V@DWH01TOERP
    WHERE NVL(SS_MODIFIED_ON,0) NOT IN (SELECT NVL(SS_MODIFIED_ON,0) FROM L1_SL_CUSTOMER_ERP)
    OR NVL(SS_CREATED_ON,0) NOT IN (SELECT NVL(SS_CREATED_ON,0) FROM L1_SL_CUSTOMER_ERP);

    IF VCUSTOMER_ERP = 0 THEN
        INSERT INTO ETL_LOG (LAYER, DATE_KEY, SOURCE, STATUS, FILE_COUNT, PER_COUNT, POST_COUNT, INSERT_TIME)
        VALUES              ('L1_SL_CUSTOMER_ERP',VDATE_KEY,'ERP','30',VSL_CUSTOMER_ERP,'','',SYSDATE);
        COMMIT;

        INSERT INTO L1_SL_CUSTOMER_ERP
        SELECT *
        FROM BMS.SYNM_BI_ACCESS_SL_CUSTOMER_V@DWH01TOERP
        WHERE NVL(SS_MODIFIED_ON,0) NOT IN (SELECT NVL(SS_MODIFIED_ON,0) FROM L1_SL_CUSTOMER_ERP)
        OR NVL(SS_CREATED_ON,0) NOT IN (SELECT NVL(SS_CREATED_ON,0) FROM L1_SL_CUSTOMER_ERP);
        COMMIT;
        
        UPDATE ETL_LOG SET STATUS = 96,
        UPDATE_TIME=SYSDATE
        WHERE DATE_KEY = VDATE_KEY
        AND LAYER = 'L1_SL_CUSTOMER_ERP';        
        COMMIT;
    ELSE
        INSERT INTO ETL_LOG (LAYER, DATE_KEY, SOURCE, STATUS, FILE_COUNT, PER_COUNT, POST_COUNT, INSERT_TIME)
        VALUES              ('L1_SL_CUSTOMER_ERP',VDATE_KEY,'ERP','34',VSL_CUSTOMER_ERP,'','',SYSDATE);
        COMMIT;
    END IF;
------------------------SYNM_BI_ACCESS_SL_CUSTTYPE_V--------------------------------------
    SELECT COUNT(STATUS) INTO VCUSTTYPE_ERP
    FROM ETL_LOG
    WHERE DATE_KEY = VDATE_KEY
    AND LAYER = 'L1_SL_CUSTTYPE_ERP'
    AND SOURCE = 'ERP';


    SELECT COUNT(*) INTO VSL_CUSTTYPE_ERP
    FROM BMS.SYNM_BI_ACCESS_SL_CUSTTYPE_V@DWH01TOERP
    WHERE NVL(SS_MODIFIED_ON,0) NOT IN (SELECT NVL(SS_MODIFIED_ON,0) FROM L1_SL_CUSTTYPE_ERP)
    OR NVL(SS_CREATED_ON,0) NOT IN (SELECT NVL(SS_CREATED_ON,0) FROM L1_SL_CUSTTYPE_ERP);

    IF VCUSTTYPE_ERP = 0 THEN
        INSERT INTO ETL_LOG (LAYER, DATE_KEY, SOURCE, STATUS, FILE_COUNT, PER_COUNT, POST_COUNT, INSERT_TIME)
        VALUES              ('L1_SL_CUSTTYPE_ERP',VDATE_KEY,'ERP','30',VSL_CUSTTYPE_ERP,'','',SYSDATE);
        COMMIT;

        INSERT INTO L1_SL_CUSTTYPE_ERP
        SELECT *
        FROM BMS.SYNM_BI_ACCESS_SL_CUSTTYPE_V@DWH01TOERP
        WHERE NVL(SS_MODIFIED_ON,0) NOT IN (SELECT NVL(SS_MODIFIED_ON,0) FROM L1_SL_CUSTTYPE_ERP)
        OR NVL(SS_CREATED_ON,0) NOT IN (SELECT NVL(SS_CREATED_ON,0) FROM L1_SL_CUSTTYPE_ERP);
        COMMIT;
        
        UPDATE ETL_LOG SET STATUS = 96,
        UPDATE_TIME=SYSDATE
        WHERE DATE_KEY = VDATE_KEY
        AND LAYER = 'L1_SL_CUSTTYPE_ERP';        
        COMMIT;
    ELSE
        INSERT INTO ETL_LOG (LAYER, DATE_KEY, SOURCE, STATUS, FILE_COUNT, PER_COUNT, POST_COUNT, INSERT_TIME)
        VALUES              ('L1_SL_CUSTTYPE_ERP',VDATE_KEY,'ERP','34',VSL_CUSTTYPE_ERP,'','',SYSDATE);
        COMMIT;
    END IF;
-----------------------SYNM_BI_ACCESS_SL_INVOICEDTL_V---------------------------
   
    SELECT COUNT(STATUS) INTO VINVOICEDTL_ERP
    FROM ETL_LOG
    WHERE DATE_KEY = VDATE_KEY
    AND LAYER = 'L1_SL_INVOICEDTL_ERP'
    AND SOURCE = 'ERP';


    SELECT COUNT(*) INTO VSL_INVOICEDTL_ERP
    FROM BMS.SYNM_BI_ACCESS_SL_INVOICEDTL_V@DWH01TOERP
    WHERE NVL(SS_MODIFIED_ON,0) NOT IN (SELECT NVL(SS_MODIFIED_ON,0) FROM L1_SL_INVOICEDTL_ERP)
    OR NVL(SS_CREATED_ON,0) NOT IN (SELECT NVL(SS_CREATED_ON,0) FROM L1_SL_INVOICEDTL_ERP);

    IF VINVOICEDTL_ERP = 0 THEN
        INSERT INTO ETL_LOG (LAYER, DATE_KEY, SOURCE, STATUS, FILE_COUNT, PER_COUNT, POST_COUNT, INSERT_TIME)
        VALUES              ('L1_SL_INVOICEDTL_ERP',VDATE_KEY,'ERP','30',VSL_INVOICEDTL_ERP,'','',SYSDATE);
        COMMIT;

        INSERT INTO L1_SL_INVOICEDTL_ERP
        SELECT *
        FROM BMS.SYNM_BI_ACCESS_SL_INVOICEDTL_V@DWH01TOERP
        WHERE NVL(SS_MODIFIED_ON,0) NOT IN (SELECT NVL(SS_MODIFIED_ON,0) FROM L1_SL_INVOICEDTL_ERP)
        OR NVL(SS_CREATED_ON,0) NOT IN (SELECT NVL(SS_CREATED_ON,0) FROM L1_SL_INVOICEDTL_ERP);
        COMMIT;
        
        UPDATE ETL_LOG SET STATUS = 96,
        UPDATE_TIME=SYSDATE
        WHERE DATE_KEY = VDATE_KEY
        AND LAYER = 'L1_SL_INVOICEDTL_ERP';        
        COMMIT;
    ELSE
        INSERT INTO ETL_LOG (LAYER, DATE_KEY, SOURCE, STATUS, FILE_COUNT, PER_COUNT, POST_COUNT, INSERT_TIME)
        VALUES              ('L1_SL_INVOICEDTL_ERP',VDATE_KEY,'ERP','34',VSL_INVOICEDTL_ERP,'','',SYSDATE);
        COMMIT;
    END IF;
----------------------SYNM_BI_ACCESS_SL_INVOICE_V------------------------
   
    SELECT COUNT(STATUS) INTO VINVOICE_ERP
    FROM ETL_LOG
    WHERE DATE_KEY = VDATE_KEY
    AND LAYER = 'L1_SL_INVOICE_ERP'
    AND SOURCE = 'ERP';


    SELECT COUNT(*) INTO VSL_INVOICE_ERP
    FROM BMS.SYNM_BI_ACCESS_SL_INVOICE_V@DWH01TOERP
    WHERE SI_NO NOT IN (SELECT SI_NO FROM L1_SL_INVOICE_ERP);

    IF VINVOICE_ERP = 0 THEN
        INSERT INTO ETL_LOG (LAYER, DATE_KEY, SOURCE, STATUS, FILE_COUNT, PER_COUNT, POST_COUNT, INSERT_TIME)
        VALUES              ('L1_SL_INVOICE_ERP',VDATE_KEY,'ERP','30',VSL_INVOICE_ERP,'','',SYSDATE);
        COMMIT;

        INSERT INTO L1_SL_INVOICE_ERP
        SELECT *
        FROM BMS.SYNM_BI_ACCESS_SL_INVOICE_V@DWH01TOERP
        WHERE SI_NO NOT IN (SELECT SI_NO FROM L1_SL_INVOICE_ERP);
        COMMIT;
        
        UPDATE ETL_LOG SET STATUS = 96,
        UPDATE_TIME=SYSDATE
        WHERE DATE_KEY = VDATE_KEY
        AND LAYER = 'L1_SL_INVOICE_ERP';        
        COMMIT;
    ELSE
        INSERT INTO ETL_LOG (LAYER, DATE_KEY, SOURCE, STATUS, FILE_COUNT, PER_COUNT, POST_COUNT, INSERT_TIME)
        VALUES              ('L1_SL_INVOICE_ERP',VDATE_KEY,'ERP','34',VSL_INVOICE_ERP,'','',SYSDATE);
        COMMIT;
    END IF;

END;
/

