--
-- SP_LAYER1_COUNT  (Procedure) 
--
CREATE OR REPLACE PROCEDURE DWH_USER.sp_layer1_count is
PDATE   DATE := TRUNC(SYSDATE-1);
ACOUNT  NUMBER;
CCOUNT  NUMBER;
DCOUNT  NUMBER;
MCOUNT  NUMBER;
RCOUNT  NUMBER;
RECOUNT NUMBER;
SCOUNT  NUMBER;
TCOUNT  NUMBER;
VCOUNT  NUMBER;
BEGIN
SELECT /*+PARALLEL(V,10)*/ COUNT(*) INTO ACOUNT
FROM L1_ADJUSTMENT_TEMP_FULL V;
INSERT INTO LAYER1_COUNT(PROCESSED_DATE,L1_ADJUSTMENT)
VALUES (PDATE,ACOUNT);
COMMIT;

SELECT /*+PARALLEL(V,10)*/ COUNT(*) INTO CCOUNT
FROM L1_CONTENT_TEMP_FULL V;
UPDATE LAYER1_COUNT SET L1_CONTENT=CCOUNT
WHERE PROCESSED_DATE=PDATE;
COMMIT;

SELECT /*+PARALLEL(V,10)*/ COUNT(*) INTO DCOUNT
FROM L1_DATA_TEMP_FULL V;
UPDATE LAYER1_COUNT SET L1_DATA=DCOUNT
WHERE PROCESSED_DATE=PDATE;
COMMIT;

SELECT /*+PARALLEL(V,10)*/ COUNT(*) INTO MCOUNT 
FROM L1_MANAGEMENT_TEMP_FULL V;
UPDATE LAYER1_COUNT SET L1_MANAGEMENT=MCOUNT
WHERE PROCESSED_DATE=PDATE;
COMMIT;

SELECT /*+PARALLEL(V,10)*/ COUNT(*) INTO RCOUNT 
FROM L1_RECHARGE_TEMP_FULL V;
UPDATE LAYER1_COUNT SET L1_RECHARGE=RCOUNT
WHERE PROCESSED_DATE=PDATE;
COMMIT;

SELECT /*+PARALLEL(V,10)*/ COUNT(*) INTO RECOUNT
FROM L1_RECURRING_TEMP_FULL V;
UPDATE LAYER1_COUNT SET L1_RECURRING=RECOUNT
WHERE PROCESSED_DATE=PDATE;
COMMIT;

SELECT /*+PARALLEL(V,10)*/ COUNT(*) INTO SCOUNT
FROM L1_SMS_TEMP_FULL  V;
UPDATE LAYER1_COUNT SET L1_SMS=SCOUNT
WHERE PROCESSED_DATE=PDATE;
COMMIT;

SELECT /*+PARALLEL(V,10)*/COUNT(*) INTO TCOUNT
FROM L1_TRANSFER_TEMP_FULL V;
UPDATE LAYER1_COUNT SET L1_TRANSFER=TCOUNT
WHERE PROCESSED_DATE=PDATE;
COMMIT;

SELECT /*+PARALLEL(V,10)*/ COUNT(*) INTO VCOUNT
FROM L1_VOICE_TEMP_FULL V;
UPDATE LAYER1_COUNT SET L1_VOICE=VCOUNT
WHERE PROCESSED_DATE=PDATE;
COMMIT;

END;
/

