--
-- SP_LAYER2_COUNT  (Procedure) 
--
CREATE OR REPLACE PROCEDURE DWH_USER.sp_layer2_count is
PDATE DATE := TRUNC(SYSDATE-1);
ACOUNT NUMBER;
CCOUNT NUMBER;
DCOUNT NUMBER;
MCOUNT NUMBER;
RCOUNT NUMBER;
RECOUNT NUMBER;
SCOUNT NUMBER;
TCOUNT NUMBER;
VCOUNT NUMBER;
BEGIN
SELECT /*+PARALLEL(V,10)*/ COUNT(*) INTO ACOUNT
FROM L2_ADJUSTMENT V,DATE_DIM DD
WHERE V.ETL_DATE_KEY=DD.DATE_KEY
AND TRUNC(DATE_VALUE)=TRUNC(SYSDATE-1);

INSERT INTO LAYER2_COUNT(PROCESSED_DATE,L2_ADJUSTMENT)
VALUES (PDATE,ACOUNT);
COMMIT;

SELECT /*+PARALLEL(V,10)*/ COUNT(*) INTO CCOUNT
FROM L2_CONTENT V,DATE_DIM DD
WHERE V.ETL_DATE_KEY=DD.DATE_KEY
AND TRUNC(DATE_VALUE)=TRUNC(SYSDATE-1);

UPDATE LAYER2_COUNT SET L2_CONTENT=CCOUNT
WHERE PROCESSED_DATE=PDATE;
COMMIT;

SELECT /*+PARALLEL(V,10)*/ COUNT(*) INTO DCOUNT
FROM L2_DATA V,DATE_DIM DD
WHERE V.ETL_DATE_KEY=DD.DATE_KEY
AND TRUNC(DATE_VALUE)=TRUNC(SYSDATE-1);

UPDATE LAYER2_COUNT SET L2_DATA=DCOUNT
WHERE PROCESSED_DATE=PDATE;
COMMIT;

SELECT /*+PARALLEL(V,10)*/ COUNT(*) INTO MCOUNT 
FROM L2_MANAGEMENT V,DATE_DIM DD
WHERE V.ETL_DATE_KEY=DD.DATE_KEY
AND TRUNC(DATE_VALUE)=TRUNC(SYSDATE-1);

UPDATE LAYER2_COUNT SET L2_MANAGEMENT=MCOUNT
WHERE PROCESSED_DATE=PDATE;
COMMIT;

SELECT /*+PARALLEL(V,10)*/ COUNT(*) INTO RCOUNT 
FROM L2_RECHARGE V,DATE_DIM DD
WHERE V.ETL_DATE_KEY=DD.DATE_KEY
AND TRUNC(DATE_VALUE)=TRUNC(SYSDATE-1);

UPDATE LAYER2_COUNT SET L2_RECHARGE=RCOUNT
WHERE PROCESSED_DATE=PDATE;
COMMIT;

SELECT /*+PARALLEL(V,10)*/ COUNT(*) INTO RECOUNT
FROM L2_RECURRING V,DATE_DIM DD
WHERE V.ETL_DATE_KEY=DD.DATE_KEY
AND TRUNC(DATE_VALUE)=TRUNC(SYSDATE-1);

UPDATE LAYER2_COUNT SET L2_RECURRING=RECOUNT
WHERE PROCESSED_DATE=PDATE;
COMMIT;

SELECT /*+PARALLEL(V,10)*/ COUNT(*) INTO SCOUNT
FROM L2_SMS V,DATE_DIM DD
WHERE V.ETL_DATE_KEY=DD.DATE_KEY
AND TRUNC(DATE_VALUE)=TRUNC(SYSDATE-1);

UPDATE LAYER2_COUNT SET L2_SMS=SCOUNT
WHERE PROCESSED_DATE=PDATE;
COMMIT;

SELECT /*+PARALLEL(V,10)*/COUNT(*) INTO TCOUNT
FROM L2_TRANSFER V,DATE_DIM DD
WHERE V.ETL_DATE_KEY=DD.DATE_KEY
AND TRUNC(DATE_VALUE)=TRUNC(SYSDATE-1);

UPDATE LAYER2_COUNT SET L2_TRANSFER=TCOUNT
WHERE PROCESSED_DATE=PDATE;
COMMIT;

SELECT /*+PARALLEL(V,10)*/ COUNT(*) INTO VCOUNT
FROM L2_VOICE V,DATE_DIM DD
WHERE V.ETL_DATE_KEY=DD.DATE_KEY
AND TRUNC(DATE_VALUE)=TRUNC(SYSDATE-1);

UPDATE LAYER2_COUNT SET L2_VOICE=VCOUNT
WHERE PROCESSED_DATE=PDATE;
COMMIT;

END;
/

