--
-- CLMA12  (View) 
--
CREATE OR REPLACE FORCE VIEW DWH_USER.CLMA12
(G372_CALLINGPARTYNUMBER, V372_CALLINGPARTYNUMBER, R375_CHARGINGPARTYNUMBER, TOTAL_REVENUE)
BEQUEATH DEFINER
AS 
SELECT G372_CALLINGPARTYNUMBER,V372_CALLINGPARTYNUMBER,R375_CHARGINGPARTYNUMBER,COALESCE(A.Sum_Col1,0) + COALESCE(B.Sum_Col1,0)+ COALESCE(C.Sum_Col2,0) as Total_Revenue

FROM

 (( select G372_CALLINGPARTYNUMBER, SUM(G448_PAY_DEBIT_AMOUNT) Sum_Col1 
 FROM  L3_DATA 
 WHERE ETL_DATE_KEY = (SELECT A.DATE_KEY FROM DATE_DIM A WHERE A.DATE_VALUE = TO_DATE(SYSDATE-9,'DD/MM/RRRR')) GROUP BY G372_CALLINGPARTYNUMBER) A
 
  FULL JOIN
  
 ( selecT V372_CALLINGPARTYNUMBER , SUM(V41_DEBIT_AMOUNT) Sum_Col1 
 FROM  L3_VOICE 
 WHERE ETL_DATE_KEY = (SELECT A.DATE_KEY FROM DATE_DIM A WHERE A.DATE_VALUE = TO_DATE(SYSDATE-9,'DD/MM/RRRR')) GROUP BY V372_CALLINGPARTYNUMBER) B 
 ON G372_CALLINGPARTYNUMBER= V372_CALLINGPARTYNUMBER
 
 Full Join
 
 (selecT R375_CHARGINGPARTYNUMBER , SUM(R41_DEBIT_AMOUNT) Sum_Col2 
FROM  L3_RECURRING 
WHERE ETL_DATE_KEY = (SELECT DATE_KEY FROM DATE_DIM  WHERE DATE_VALUE = TO_DATE(SYSDATE-9,'DD/MM/RRRR')) GROUP BY R375_CHARGINGPARTYNUMBER) C
ON  R375_CHARGINGPARTYNUMBER= G372_CALLINGPARTYNUMBER or R375_CHARGINGPARTYNUMBER=V372_CALLINGPARTYNUMBER);


