--
-- CLMA18  (View) 
--
CREATE OR REPLACE FORCE VIEW DWH_USER.CLMA18
(BTS_ID1, BTS_ID2, TOTAL_REVENUE)
BEQUEATH DEFINER
AS 
select BTS_ID1, BTS_ID2,COALESCE(A.Sum_Col1,0) + COALESCE(B.Sum_Col1,0) as Total_Revenue from
( select SUBSTR (G379_CALLINGCELLID,LENGTH(G379_CALLINGCELLID)-2,2) as BTS_ID1, SUM(G448_PAY_DEBIT_AMOUNT) Sum_Col1 
 FROM  L3_DATA 
 WHERE ETL_DATE_KEY = (SELECT A.DATE_KEY FROM DATE_DIM A WHERE A.DATE_VALUE = TO_DATE(SYSDATE-9,'DD/MM/RRRR')) GROUP BY  SUBSTR (G379_CALLINGCELLID,LENGTH(G379_CALLINGCELLID)-2,2)) A
 
  FULL JOIN
  
 ( selecT SUBSTR (V381_CALLINGCELLID,LENGTH(V381_CALLINGCELLID)-2,2) as BTS_ID2, SUM(V41_DEBIT_AMOUNT) Sum_Col1 
 FROM  L3_VOICE 
 WHERE ETL_DATE_KEY = (SELECT A.DATE_KEY FROM DATE_DIM A WHERE A.DATE_VALUE = TO_DATE(SYSDATE-9,'DD/MM/RRRR')) GROUP BY SUBSTR (V381_CALLINGCELLID,LENGTH(V381_CALLINGCELLID)-2,2)) B 
 ON BTS_ID1=BTS_ID2;


