--
-- CLMC1  (View) 
--
CREATE OR REPLACE FORCE VIEW DWH_USER.CLMC1
(G372_CALLINGPARTYNUMBER, DATA_REVENUE, V372_CALLINGPARTYNUMBER, VOICE_REVENUE, R375_CHARGINGPARTYNUMBER, 
 VAS_REVENUE)
BEQUEATH DEFINER
AS 
SELECT "G372_CALLINGPARTYNUMBER","DATA_REVENUE","V372_CALLINGPARTYNUMBER","VOICE_REVENUE","R375_CHARGINGPARTYNUMBER","VAS_REVENUE" FROM
(SELECT G372_CALLINGPARTYNUMBER, SUM(G448_PAY_DEBIT_AMOUNT) Data_Revenue
FROM L3_DATA
GROUP BY G372_CALLINGPARTYNUMBER)

FULL JOIN

(SELECT V372_CALLINGPARTYNUMBER, SUM(V41_DEBIT_AMOUNT ) Voice_Revenue
FROM L3_VOICE
GROUP BY V372_CALLINGPARTYNUMBER
)
ON G372_CALLINGPARTYNUMBER=V372_CALLINGPARTYNUMBER

FULL JOIN

(select  R375_CHARGINGPARTYNUMBER,sum(R41_DEBIT_AMOUNT) Vas_revenue
from L3_RECURRING
group by R375_CHARGINGPARTYNUMBER
)
on R375_CHARGINGPARTYNUMBER=G372_CALLINGPARTYNUMBER or R375_CHARGINGPARTYNUMBER=V372_CALLINGPARTYNUMBER;


