--
-- MISSING_CDR_CHECK  (View) 
--
CREATE OR REPLACE FORCE VIEW DWH_USER.MISSING_CDR_CHECK
(PROCESS_DATE, SOURCE, "cdr_head", "source_dir", "missing cdr", 
 MAIN_SOURCE)
BEQUEATH DEFINER
AS 
SELECT TRUNC(SYSDATE-1) PROCESS_DATE,A.SOURCE,A.COUNT AS "cdr_head",B.COUNT AS "source_dir", B.COUNT-A.COUNT AS "missing cdr", MAIN_SOURCE
FROM
(
SELECT /*+PARALLEL(Q,16)*/SOURCE,COUNT(UNIQUE FILE_NAME) AS COUNT,'cbs' AS MAIN_SOURCE
FROM CDR_HEAD Q
WHERE TRUNC(PROCESS_DATE) BETWEEN TRUNC(SYSDATE-1) AND TRUNC(SYSDATE)
AND FILE_NAME LIKE '%'||(SELECT TO_CHAR(DATE_VALUE,'RRRRMMDD')AS FILE_NAME  FROM DATE_DIM WHERE TRUNC(DATE_VALUE)=TRUNC(SYSDATE-1))||'%'
AND SOURCE IN ('adj','cm','com','data','mon','sms','transfer','voice','vou')
GROUP BY   SOURCE
UNION ALL
SELECT /*+PARALLEL(Q,16)*/SOURCE,COUNT(UNIQUE FILE_NAME) AS COUNT,'fuo' AS MAIN_SOURCE
FROM CDR_HEAD Q
WHERE TRUNC(PROCESS_DATE) BETWEEN TRUNC(SYSDATE-1) AND TRUNC(SYSDATE)
AND FILE_NAME LIKE '%'||(SELECT TO_CHAR(DATE_VALUE,'RRRRMMDD')AS FILE_NAME  FROM DATE_DIM WHERE TRUNC(DATE_VALUE)=TRUNC(SYSDATE-1))||'%'
AND SOURCE LIKE '%fuo%'
GROUP BY SOURCE
UNION ALL
SELECT  SOURCE,COUNT(UNIQUE FILE_NAME) AS COUNT,'msc' AS MAIN_SOURCE
FROM CDR_HEAD@DWH01TODWH03 
WHERE TRUNC(PROCESS_DATE) BETWEEN TRUNC(SYSDATE-1) AND TRUNC(SYSDATE)
AND FILE_NAME LIKE '%'||(SELECT TO_CHAR(DATE_VALUE,'RRRRMMDD')AS FILE_NAME  FROM DATE_DIM WHERE TRUNC(DATE_VALUE)=TRUNC(SYSDATE-1))||'%'
GROUP BY   SOURCE
UNION ALL
SELECT SOURCE,COUNT(UNIQUE FILE_NAME) AS COUNT,'mfs' AS MAIN_SOURCE
FROM CDR_HEAD@DWH01TODWH03
WHERE TRUNC(PROCESS_DATE) BETWEEN TRUNC(SYSDATE-1) AND TRUNC(SYSDATE)
AND SOURCE IN ('smsc','ussd','cgw')
AND FILE_NAME LIKE '%'||(SELECT TO_CHAR(DATE_VALUE,'RRRRMMDD')AS FILE_NAME  FROM DATE_DIM WHERE TRUNC(DATE_VALUE)=TRUNC(SYSDATE-3))||'%'
GROUP BY SOURCE
)A,
(SELECT  SOURCE, SUM(COUNT)AS COUNT
FROM ROW_CDR_COUNT_LOG
WHERE TRUNC(TO_DATE(PROCESS_DATE,'DD/MM/RRRR'))=TRUNC(SYSDATE-1)
GROUP BY SOURCE) B
WHERE A.SOURCE=B.SOURCE(+)
ORDER BY MAIN_SOURCE,SOURCE;


