--
-- MSISDN_TYPE  (View) 
--
CREATE OR REPLACE FORCE VIEW DWH_USER.MSISDN_TYPE
(RE6_PRI_IDENTITY, PAY_TYPE_ID, PAY_TYPE_NAME)
BEQUEATH DEFINER
AS 
SELECT a.RE6_PRI_IDENTITY, b.PAY_TYPE_ID, b.PAY_TYPE_NAME
     FROM l1_recharge a, paytype_dim b
    WHERE a.RE490_PAYTYPE = b.PAY_TYPE_ID
    GROUP BY RE6_PRI_IDENTITY, b.PAY_TYPE_ID, b.PAY_TYPE_NAME;


