--
-- TAREQ_L2_SMS_VIEW  (View) 
--
CREATE OR REPLACE FORCE VIEW DWH_USER.TAREQ_L2_SMS_VIEW
(MSISDN)
BEQUEATH DEFINER
AS 
SELECT DISTINCT S22_PRI_IDENTITY AS MSISDN
     FROM L2_SMS
    WHERE     S387_CHARGINGTIME_KEY =
                 (SELECT DATE_KEY
                    FROM DATE_DIM
                   WHERE TRUNC (DATE_VALUE) = TRUNC (SYSDATE - 2))
          AND S378_SERVICEFLOW = '1';


