--
-- TEST_BC_OFFERING_INST_101_VIEW  (View) 
--
CREATE OR REPLACE FORCE VIEW DWH_USER.TEST_BC_OFFERING_INST_101_VIEW
(PROCESSED_DATE, SUB_ID, TYPE, OFFERID, EFF_DATE, 
 EXP_DATE, EVENT_DATE)
BEQUEATH DEFINER
AS 
SELECT "PROCESSED_DATE","SUB_ID","TYPE","OFFERID","EFF_DATE","EXP_DATE","EVENT_DATE" FROM TEST_BC_OFFERING_INST_101 A
WHERE TRUNC(A.PROCESSED_DATE)=TRUNC(TO_DATE('24082020','ddmmrrrr'));


