--
-- TEST_SUB_IDEN_101_VIEW  (View) 
--
CREATE OR REPLACE FORCE VIEW DWH_USER.TEST_SUB_IDEN_101_VIEW
(PROCESSED_DATE, SUB_ID, MSISDN, EVENT_DATE)
BEQUEATH DEFINER
AS 
SELECT "PROCESSED_DATE","SUB_ID","MSISDN","EVENT_DATE" FROM TEST_SUB_IDEN_101 A
WHERE TRUNC(A.PROCESSED_DATE)=TRUNC(TO_DATE('24082020','ddmmrrrr'));


