--
-- F_PARTITION_MSC_2  (Function) 
--
CREATE OR REPLACE FUNCTION DWH_USER03.F_PARTITION_MSC_2
   RETURN VARCHAR2
AS
   VPARTITION_NAME   VARCHAR2 (100);
BEGIN
   SELECT PARTITION_NAME
     INTO VPARTITION_NAME
     FROM (SELECT PARTITION_NAME,
                  ROW_NUMBER () OVER (ORDER BY PARTITION_POSITION DESC) LS
             FROM ALL_TAB_PARTITIONS
            WHERE TABLE_NAME = 'L1_MSC')
    WHERE LS = 2;

   RETURN VPARTITION_NAME;
END;
/

