--
-- P_IMEI_MSISDN_FCT  (Procedure) 
--
CREATE OR REPLACE PROCEDURE DWH_USER03.P_IMEI_MSISDN_FCT IS
BEGIN
EXECUTE IMMEDIATE 'TRUNCATE TABLE IMEI_MSISDN_FCT_LD DROP STORAGE';
INSERT INTO IMEI_MSISDN_FCT_LD
SELECT DATE_KEY, M04_MSISDNAPARTY, PREFERRED
FROM
(SELECT DATE_KEY,M04_MSISDNAPARTY,LEN,M03_IMEI,
CASE
WHEN LEN < 14
THEN NULL
WHEN LEN > 13
THEN M03_IMEI

END PREFERRED

FROM
( 
SELECT /*+ palallel (A,16)*/ B.DATE_KEY,M04_MSISDNAPARTY,M03_IMEI,LENGTH(M03_IMEI) LEN
FROM L1_MSC A, DATE_DIM B
WHERE PROCESSED_DATE=TO_DATE(SYSDATE-1,'DD/MM/RRRR') 
AND REGEXP_LIKE(M03_IMEI, '^[[:digit:]]+$')
AND TO_CHAR(B.DATE_VALUE,'RRRRMMDD')=SUBSTR((M07_ANSWERTIMESTAMP),1,8)
--AND SUBSTR((M07_ANSWERTIMESTAMP),1,8)=(SELECT TO_CHAR(DATE_VALUE,'RRRRMMDD') AS DATE_VALUE FROM DATE_DIM WHERE TO_CHAR(DATE_VALUE,'RRRRMMDD')=TO_CHAR(SYSDATE-1,'RRRRMMDD'))
)
);
COMMIT;

INSERT INTO IMEI_MSISDN_FCT
SELECT DATE_KEY, MSISDN, IMEI
FROM IMEI_MSISDN_FCT_LD
GROUP BY DATE_KEY, MSISDN, IMEI;
COMMIT;

END;
/

