--
-- P_L1_NOKIA_TO_L1_MSC  (Procedure) 
--
CREATE OR REPLACE PROCEDURE DWH_USER03.P_L1_NOKIA_TO_L1_MSC IS
    VCOUNT NUMBER;
    VDATE_KEY NUMBER;
    VSTATUS NUMBER;
    VTMPSTATUS NUMBER;
BEGIN
    
    SELECT DATE_KEY INTO VDATE_KEY FROM DATE_DIM
    WHERE DATE_KEY = (SELECT DATE_KEY FROM DATE_DIM  WHERE TRUNC(DATE_VALUE) = TRUNC(SYSDATE-1));
    
    SELECT COUNT(STATUS) INTO VSTATUS
    FROM ETL_LOG
    WHERE DATE_KEY = (SELECT DATE_KEY FROM DATE_DIM  WHERE TRUNC(DATE_VALUE) = TRUNC(SYSDATE-1))
    AND LAYER = 'L1_MSC_NOKIA'
    AND SOURCE ='NOKIA';
    
    SELECT STATUS INTO VTMPSTATUS
    FROM TEMP_TABLE_ALTER_LOG
    WHERE TRUNC(ALTER_DATE)=TRUNC(SYSDATE)
    AND TABLE_NAME = 'L1_MSC_NOKIA';
    
    IF VSTATUS = 0 AND VTMPSTATUS =96 THEN
        INSERT INTO ETL_LOG (LAYER, DATE_KEY, SOURCE, STATUS, FILE_COUNT, PER_COUNT, POST_COUNT, INSERT_TIME)
        VALUES              ('L1_MSC_NOKIA',VDATE_KEY,'NOKIA','30',VCOUNT,'','',SYSDATE);
        COMMIT;
        
        INSERT INTO L1_MSC( PROCESSED_DATE, FILE_NAME, M01_CALLTYPE, M02_IMSI, M03_IMEI, M04_MSISDNAPARTY, M05_MSISDNBPARTY, M07_ANSWERTIMESTAMP, M08_CALLDUR, M09_LOCATION, M10_LAST_LOCATION, M11_CAUSEOFTERMINATION,M07_ANSWERTIMESTAMP_KEY, M07_ANSWERTIMESTAMP_HOUR)
        SELECT PROCESSED_DATE,FILE_NAME, RECORD_NAME, MN12_IMSI,IMEI, MN01_SERVEDMSISDN, MN02_CALLINGNUMBER, MN03_ANSWERTIME, CALLDURATION, LOCATION,  M09_LAST_LOCATION,TERMINATION_NAME,MN03_ANSWERTIME_KEY,MN03_ANSWERTIME_HOUR
        FROM
        (SELECT PROCESSED_DATE,FILE_NAME, RECORD_NAME, MN12_IMSI,MN11_IMEI, MN01_SERVEDMSISDN, MN02_CALLINGNUMBER,MN03_ANSWERTIME, CALLDURATION, MN09_LOCATION , M09_LAST_LOCATION,MN13_CAUSEFORTERM,TERMINATION_NAME,MN03_ANSWERTIME_KEY,MN03_ANSWERTIME_HOUR,

        CASE
        WHEN LENGTH(MN11_IMEI)>13
        THEN MN11_IMEI
        WHEN LENGTH(MN11_IMEI)<14
        THEN NULL

        END IMEI,

        CASE
        WHEN LENGTH(MN09_LOCATION)=15
        THEN MN09_LOCATION
        WHEN LENGTH(MN09_LOCATION)!=15
        THEN NULL

        END LOCATION

        FROM
        (SELECT  TRUNC(SYSDATE-1)AS PROCESSED_DATE,FILE_NAME, RECORD_NAME, MN12_IMSI,MN11_IMEI, LPAD(MN01_SERVEDMSISDN,13,880) AS MN01_SERVEDMSISDN, MN02_CALLINGNUMBER, MN03_ANSWERTIME,MN04_CALLDURATION/1000 AS CALLDURATION, LPAD(LPAD(MN07_FSTLAC,5,0)||LPAD(MN08_FSTCI,5,0),15,47004) AS MN09_LOCATION ,LPAD(LPAD(MN09_LASTLAC,5,0)||LPAD(MN10_LASTCI,5,0),15,47004) AS M09_LAST_LOCATION,MN13_CAUSEFORTERM,TERMINATION_NAME,
        D.DATE_KEY AS MN03_ANSWERTIME_KEY, SUBSTR(MN03_ANSWERTIME,9,4) AS MN03_ANSWERTIME_HOUR
        FROM L1_MSC_NOKIA A, RECORD_TYPE_DIM B, TERMINATION_DIM C, DATE_DIM D
        WHERE substr(MN03_ANSWERTIME,1,8)=TO_CHAR(D.DATE_VALUE,'RRRRMMDD')
        AND MN05_RECORDTYPE=RECORD_ID
        AND MN13_CAUSEFORTERM=TERMINATION_ID(+)
        AND REGEXP_LIKE(NVL(MN04_CALLDURATION,0), '^[[:digit:]]+$')
        AND MN01_SERVEDMSISDN IS NOT NULL
        AND MN02_CALLINGNUMBER IS NOT NULL
        AND MN03_ANSWERTIME IS NOT NULL
        )
        )
        group by PROCESSED_DATE,FILE_NAME, RECORD_NAME, MN12_IMSI,IMEI, MN01_SERVEDMSISDN, MN02_CALLINGNUMBER,MN03_ANSWERTIME, CALLDURATION, LOCATION,  M09_LAST_LOCATION,TERMINATION_NAME,MN03_ANSWERTIME_KEY,MN03_ANSWERTIME_HOUR
        ;
        commit;

    UPDATE ETL_LOG SET STATUS = 96,
    UPDATE_TIME=SYSDATE
    WHERE DATE_KEY = VDATE_KEY
    AND LAYER = 'L1_MSC_NOKIA';        
        COMMIT;
  ELSE
     INSERT INTO ETL_LOG (LAYER, DATE_KEY, SOURCE, STATUS, FILE_COUNT, PER_COUNT, POST_COUNT, INSERT_TIME)
     VALUES              ('L1_MSC_NOKIA',VDATE_KEY,'NOKIA','34',VCOUNT,'','',SYSDATE);
    COMMIT;
  END IF;
EXCEPTION
 WHEN OTHERS THEN NULL;
END;
/

