--
-- SP_LUHN_ALG_TEST  (Procedure) 
--
CREATE OR REPLACE PROCEDURE DWH_USER03.SP_LUHN_ALG_TEST( IN_DATE_KEY VARCHAR2,IN_MSISDN VARCHAR2,IN_IMEI VARCHAR2,IMSI VARCHAR2 ) AS
   C_IN_VAL VARCHAR2(20);
   C_SUM  NUMBER(20) := 0; 
   INT_VAL  NUMBER(20) := 0;
   I NUMBER(20) :=0;
   VRETURN VARCHAR2(20);
   LANTH_RETURN NUMBER;
   BEGIN
      C_IN_VAL := SUBSTR(IN_IMEI,1,14);                
      I := LENGTH( C_IN_VAL );
      
      WHILE I > 0 LOOP
         IF ( MOD( I, 2 ) >0) THEN
         C_SUM := C_SUM + CAST( SUBSTR(C_IN_VAL, I, 1 ) AS NUMBER );
         ELSE
               INT_VAL := CAST( SUBSTR(C_IN_VAL, I, 1 ) AS NUMBER )*2;
                IF ( LENGTH( TO_CHAR(INT_VAL) ) > 1 ) THEN
                C_SUM := C_SUM + CAST( SUBSTR(TO_CHAR(INT_VAL),1,1) AS NUMBER )+ CAST( SUBSTR(TO_CHAR(INT_VAL),2,1) AS NUMBER) ;
                ELSE
                C_SUM := C_SUM + INT_VAL ; 
                END IF;   
         END IF;
         I := I - 1;
      END LOOP;
   VRETURN:= C_IN_VAL || (10-MOD( C_SUM, 10 ));
   
   LANTH_RETURN :=LENGTH(VRETURN);
   
   BEGIN
       IF LANTH_RETURN > 16 THEN
        INSERT INTO TAREQ_IMEI_MSISDN_FCT_LD(DATE_KEY, MSISDN, IMEI, RAW_IIMEI, IMSI)
        VALUES (IN_DATE_KEY,IN_MSISDN,SUBSTR(VRETURN,1,14)||'0',IN_IMEI,IMSI);
        COMMIT;
       ELSIF LANTH_RETURN= 2 THEN
       INSERT INTO TAREQ_IMEI_MSISDN_FCT_LD(DATE_KEY, MSISDN, IMEI, RAW_IIMEI, IMSI)
        VALUES (IN_DATE_KEY,IN_MSISDN,NULL,IN_IMEI,IMSI);
       ELSE
        INSERT INTO TAREQ_IMEI_MSISDN_FCT_LD(DATE_KEY, MSISDN, IMEI, RAW_IIMEI, IMSI)
        VALUES (IN_DATE_KEY,IN_MSISDN,SUBSTR(VRETURN,1,15),IN_IMEI,IMSI);
        COMMIT;
       END IF;
   END;
   
END SP_LUHN_ALG_TEST;
/

