--
-- TAREQ_IMEI_FCT  (Procedure) 
--
CREATE OR REPLACE PROCEDURE DWH_USER03.TAREQ_IMEI_FCT ( IN_DATE VARCHAR2) IS
CURSOR C1 IS
SELECT DATE_KEY, M04_MSISDNAPARTY, IMEI,M02_IMSI
FROM
(SELECT DATE_KEY,M04_MSISDNAPARTY,LEN,M02_IMSI,M03_IMEI,
CASE
WHEN LEN < 14
THEN NULL
WHEN LEN > 13
THEN M03_IMEI

END IMEI

FROM
( 
SELECT /*+ palallel (A,16)*/ B.DATE_KEY,M04_MSISDNAPARTY,M02_IMSI,M03_IMEI,LENGTH(M03_IMEI) LEN
FROM L1_MSC A, DATE_DIM B
WHERE TO_DATE(PROCESSED_DATE,'DD/MM/RRRR')=TO_DATE(TO_DATE(IN_DATE,'RRRR/MM/DD'),'DD/MM/RRRR')
AND REGEXP_LIKE(M03_IMEI, '^[[:digit:]]+$')
AND TO_CHAR(B.DATE_VALUE,'RRRRMMDD')=SUBSTR((M07_ANSWERTIMESTAMP),1,8)
)
)
GROUP BY DATE_KEY, M04_MSISDNAPARTY, IMEI,M02_IMSI;


BEGIN

   FOR REC IN C1
   LOOP

     SP_LUHN_ALG_TEST(REC.DATE_KEY,REC.M04_MSISDNAPARTY,REC.IMEI,REC.M02_IMSI);

   END LOOP;
   
   BEGIN
    INSERT INTO TAREQ_IMEI_MSISDN_FCT(DATE_KEY, MSISDN, IMEI, IMSI)
    SELECT DATE_KEY, MSISDN, IMEI, IMSI
    FROM TAREQ_IMEI_MSISDN_FCT_LD
    WHERE DATE_KEY=(SELECT DATE_KEY FROM DATE_DIM WHERE TRUNC(DATE_VALUE)=TRUNC(TO_DATE(IN_DATE,'RRRRMMDD')))
    AND MSISDN||IMEI NOT IN (SELECT MSISDN||IMEI FROM TAREQ_IMEI_MSISDN_FCT)
    GROUP BY DATE_KEY, MSISDN, IMEI, IMSI;
    COMMIT;
    EXECUTE IMMEDIATE 'TRUNCATE TABLE TAREQ_IMEI_MSISDN_FCT_LD DROP STORAGE';
   END;
NULL;
END;
/

