--
-- MSISDN_COMPARE_7  (Procedure) 
--
CREATE OR REPLACE PROCEDURE DWH_USER.MSISDN_COMPARE_7 IS
    VDATE_KEY        VARCHAR2(12);
BEGIN

    SELECT DATE_KEY INTO VDATE_KEY 
    FROM DATE_DIM
    WHERE DATE_KEY = (SELECT A.DATE_KEY FROM DATE_DIM A WHERE A.DATE_VALUE = TO_DATE (SYSDATE-1,'dd/mm/rrrr'));
    
    INSERT INTO MSISDN_FOR_SYSDATE_1_BASE
    SELECT VDATE_KEY,MSISDN,CALLINGCELLID,CHARGINGTIME_HOUR,LCOUNT
    FROM
    (
    SELECT MSISDN,CALLINGCELLID,CHARGINGTIME_HOUR,LCOUNT,RANK() OVER (PARTITION BY MSISDN ORDER BY CHARGINGTIME_HOUR ASC, LCOUNT DESC) AS LAST_KEY
    FROM
    (
    SELECT MSISDN,CALLINGCELLID,CHARGINGTIME_HOUR,SUM(LCOUNT) AS LCOUNT
    FROM
    (
    SELECT MSISDN,CALLINGCELLID,CHARGINGTIME_HOUR,LCOUNT
    FROM
    (
    SELECT MSISDN, V381_CALLINGCELLID AS CALLINGCELLID, LCOUNT, V387_CHARGINGTIME_HOUR AS CHARGINGTIME_HOUR 
    FROM MSISDN_VOICE_FOR_SYSDATE_1
    WHERE DATE_KEY=VDATE_KEY
    )
    UNION ALL
    SELECT MSISDN,CALLINGCELLID,CHARGINGTIME_HOUR,LCOUNT
    FROM
    (
    SELECT MSISDN, G379_CALLINGCELLID AS CALLINGCELLID, LCOUNT, G383_CHARGINGTIME_HOUR AS CHARGINGTIME_HOUR
    FROM MSISDN_DATA_FOR_SYSDATE_1
    WHERE DATE_KEY=VDATE_KEY
    )
    )
    GROUP BY MSISDN,CALLINGCELLID,CHARGINGTIME_HOUR
    )
    )
    WHERE LAST_KEY=1;
    COMMIT;
/*
    DELETE FROM MSISDN_FOR_SYSDATE_1_BASE A
    WHERE ROWID > (SELECT MIN(ROWID) FROM MSISDN_FOR_SYSDATE_1_BASE B
    WHERE B.DATE_KEY=VDATE_KEY
    AND A.DATE_KEY=B.DATE_KEY
    AND B.MSISDN=A.MSISDN);
    COMMIT;
    */

END;
/

