--
-- MSISDN_COMPARE_10  (Procedure) 
--
CREATE OR REPLACE PROCEDURE DWH_USER.MSISDN_COMPARE_10 IS
    VDATE_KEY        VARCHAR2(12);
BEGIN

    SELECT DATE_KEY INTO VDATE_KEY
    FROM DATE_DIM
    WHERE DATE_KEY = (SELECT A.DATE_KEY FROM DATE_DIM A WHERE A.DATE_VALUE = TO_DATE (SYSDATE-1,'dd/mm/rrrr'));
   
    
    MERGE INTO MSISDN_COMPARE A
    USING (SELECT /*+ PARALLEL(A,8) */ DATE_KEY, MSISDN, UPAZILA_CODE2
    FROM MSISDN_FOR_SYSDATE_1_BASE A, ZONE_DIM_WITH_CODE B
    WHERE DATE_KEY=VDATE_KEY
    AND A.CALLINGCELLID = B.CGI) V
    ON (A.DATE_KEY=V.DATE_KEY AND A.MSISDN=V.MSISDN)
    WHEN MATCHED THEN
    UPDATE SET A.UPAZILA_CODE2=V.UPAZILA_CODE2;
    COMMIT;

END;
/

