--
-- MSISDN_COMPARE_1  (Procedure) 
--
CREATE OR REPLACE PROCEDURE DWH_USER.MSISDN_COMPARE_1 IS
    VDATE_KEY        VARCHAR2(12);
    VPERTITION       VARCHAR2(50);
BEGIN

    SELECT DATE_KEY INTO VDATE_KEY 
    FROM DATE_DIM
    WHERE DATE_KEY = (SELECT A.DATE_KEY FROM DATE_DIM A WHERE A.DATE_VALUE = TO_DATE (SYSDATE-1,'dd/mm/rrrr'));
    
    SELECT 'DATA_'||DATE_KEY INTO VPERTITION
    FROM DATE_DIM
    WHERE DATE_KEY = (SELECT A.DATE_KEY FROM DATE_DIM A WHERE A.DATE_VALUE = TO_DATE (SYSDATE,'dd/mm/rrrr'));
    
    
    INSERT INTO MSISDN_DATA_FOR_SYSDATE_1_LD
    SELECT VDATE_KEY,MSISDN,G379_CALLINGCELLID,MAX(LCOUNT) AS LCOUNT
    FROM
    (SELECT G372_CALLINGPARTYNUMBER AS MSISDN,G379_CALLINGCELLID, COUNT(G372_CALLINGPARTYNUMBER) LCOUNT
    FROM L3_DATA
    WHERE G383_CHARGINGTIME_KEY = (SELECT DATE_KEY FROM DATE_DIM WHERE TRUNC(DATE_VALUE)=TRUNC(SYSDATE-1))
    GROUP BY G372_CALLINGPARTYNUMBER,G379_CALLINGCELLID
    )
    GROUP BY MSISDN,G379_CALLINGCELLID;
    COMMIT;
END;
/

