--
-- MSISDN_COMPARE_5  (Procedure) 
--
CREATE OR REPLACE PROCEDURE DWH_USER.MSISDN_COMPARE_5 IS
    VDATE_KEY        VARCHAR2(12);
    VPERTITION       VARCHAR2(50);
BEGIN

    SELECT 'VOICE_'||DATE_KEY INTO VPERTITION
    FROM DATE_DIM
    WHERE DATE_KEY = (SELECT A.DATE_KEY FROM DATE_DIM A WHERE A.DATE_VALUE = TO_DATE (SYSDATE,'dd/mm/rrrr'));
    
    SELECT DATE_KEY INTO VDATE_KEY 
    FROM DATE_DIM
    WHERE DATE_KEY = (SELECT A.DATE_KEY FROM DATE_DIM A WHERE A.DATE_VALUE = TO_DATE (SYSDATE-1,'dd/mm/rrrr'));
    
    INSERT INTO MSISDN_VOICE_FOR_SYSDATE_1
    SELECT VDATE_KEY,A.MSISDN,A.V381_CALLINGCELLID,LCOUNT,B.V387_CHARGINGTIME_HOUR
    FROM MSISDN_VOICE_FOR_SYSDATE_1_LD A, L3_VOICE B--PARTITION (VOICE_2346) B
    WHERE A.DATE_KEY=VDATE_KEY
    AND B.V387_CHARGINGTIME_KEY = (SELECT DATE_KEY FROM DATE_DIM WHERE TRUNC(DATE_VALUE)=TRUNC(SYSDATE-1))
    AND A.MSISDN=B.V372_CALLINGPARTYNUMBER
    AND A.V381_CALLINGCELLID=B.V381_CALLINGCELLID
    GROUP BY A.MSISDN,A.V381_CALLINGCELLID,LCOUNT,B.V387_CHARGINGTIME_HOUR;
    COMMIT;        
END;
/

