--
-- MSISDN_COMPARE_3  (Procedure) 
--
CREATE OR REPLACE PROCEDURE DWH_USER.MSISDN_COMPARE_3 IS
    VDATE_KEY        VARCHAR2(12);
BEGIN

    SELECT DATE_KEY INTO VDATE_KEY 
    FROM DATE_DIM
    WHERE DATE_KEY = (SELECT A.DATE_KEY FROM DATE_DIM A WHERE A.DATE_VALUE = TO_DATE (SYSDATE-1,'dd/mm/rrrr'));
    
    INSERT INTO MSISDN_DATA_FOR_SYSDATE_1_BASE
    SELECT VDATE_KEY,MSISDN,G379_CALLINGCELLID,G383_CHARGINGTIME_HOUR,LCOUNT
    FROM
    (
    SELECT MSISDN,G379_CALLINGCELLID,LCOUNT,G383_CHARGINGTIME_HOUR, RANK() OVER (PARTITION BY MSISDN ORDER BY G383_CHARGINGTIME_HOUR ASC, LCOUNT DESC) AS LAST_KEY
    FROM MSISDN_DATA_FOR_SYSDATE_1
    WHERE DATE_KEY=VDATE_KEY
    )
    WHERE LAST_KEY = 1
    GROUP BY MSISDN,G379_CALLINGCELLID,G383_CHARGINGTIME_HOUR,LCOUNT;
    COMMIT;
    
END;
/

