--
-- MSISDN_COMPARE_9  (Procedure) 
--
CREATE OR REPLACE PROCEDURE DWH_USER.MSISDN_COMPARE_9 IS
    VDATE_KEY1        VARCHAR2(12);
    VDATE_KEY2        VARCHAR2(12);
BEGIN

    SELECT DATE_KEY INTO VDATE_KEY1 
    FROM DATE_DIM
    WHERE DATE_KEY = (SELECT A.DATE_KEY FROM DATE_DIM A WHERE A.DATE_VALUE = TO_DATE (SYSDATE-1,'dd/mm/rrrr'));
    
    SELECT DATE_KEY INTO VDATE_KEY2 
    FROM DATE_DIM
    WHERE DATE_KEY = (SELECT A.DATE_KEY FROM DATE_DIM A WHERE A.DATE_VALUE = TO_DATE (SYSDATE-2,'dd/mm/rrrr'));
    
    INSERT INTO MSISDN_COMPARE(DATE_KEY,MSISDN,UPAZILA_CODE1)
    SELECT VDATE_KEY1,MSISDN, UPAZILA_CODE2
    FROM MSISDN_FOR_SYSDATE_2_BASE A, ZONE_DIM_WITH_CODE B
    WHERE DATE_KEY= VDATE_KEY2
    AND A.CALLINGCELLID = B.CGI;
    COMMIT;

END;
/

