--
-- MSISDN_COMPARE_8  (Procedure) 
--
CREATE OR REPLACE PROCEDURE DWH_USER.MSISDN_COMPARE_8 IS
    VDATE_KEY        VARCHAR2(12);
BEGIN

    SELECT DATE_KEY INTO VDATE_KEY 
    FROM DATE_DIM
    WHERE DATE_KEY = (SELECT A.DATE_KEY FROM DATE_DIM A WHERE A.DATE_VALUE = TO_DATE (SYSDATE-2,'dd/mm/rrrr'));
    
    INSERT INTO MSISDN_FOR_SYSDATE_2_BASE 
    SELECT * FROM MSISDN_FOR_SYSDATE_1_BASE
    WHERE DATE_KEY=VDATE_KEY;
    COMMIT;


END;
/

