--
-- MSISDN_COMPARE_6  (Procedure) 
--
CREATE OR REPLACE PROCEDURE DWH_USER.MSISDN_COMPARE_6 IS
    VDATE_KEY        VARCHAR2(12);
BEGIN

    SELECT DATE_KEY INTO VDATE_KEY 
    FROM DATE_DIM
    WHERE DATE_KEY = (SELECT A.DATE_KEY FROM DATE_DIM A WHERE A.DATE_VALUE = TO_DATE (SYSDATE-1,'dd/mm/rrrr'));
    
    INSERT INTO  MSISDN_VOICE_FOR_SYSDATE_1_BASE
    SELECT VDATE_KEY,MSISDN,V381_CALLINGCELLID,V387_CHARGINGTIME_HOUR,LCOUNT
    FROM
    (
    SELECT MSISDN,V381_CALLINGCELLID,LCOUNT,V387_CHARGINGTIME_HOUR, RANK() OVER (PARTITION BY MSISDN ORDER BY V387_CHARGINGTIME_HOUR ASC, LCOUNT DESC) AS LAST_KEY
    FROM MSISDN_VOICE_FOR_SYSDATE_1
    WHERE DATE_KEY=VDATE_KEY
    )
    WHERE LAST_KEY = 1
    GROUP BY  MSISDN,V381_CALLINGCELLID,V387_CHARGINGTIME_HOUR,LCOUNT;  
    COMMIT;      
END;
/

