--
-- MSISDN_COMPARE_4  (Procedure) 
--
CREATE OR REPLACE PROCEDURE DWH_USER.MSISDN_COMPARE_4 IS
    VDATE_KEY        VARCHAR2(12);
    VPERTITION       VARCHAR2(50);
BEGIN

    SELECT 'VOICE_'||DATE_KEY INTO VPERTITION
    FROM DATE_DIM
    WHERE DATE_KEY = (SELECT A.DATE_KEY FROM DATE_DIM A WHERE A.DATE_VALUE = TO_DATE (SYSDATE,'dd/mm/rrrr'));

    SELECT DATE_KEY INTO VDATE_KEY 
    FROM DATE_DIM
    WHERE DATE_KEY = (SELECT A.DATE_KEY FROM DATE_DIM A WHERE A.DATE_VALUE = TO_DATE (SYSDATE-1,'dd/mm/rrrr'));
    
    
    INSERT INTO MSISDN_VOICE_FOR_SYSDATE_1_LD
    SELECT VDATE_KEY,MSISDN,V381_CALLINGCELLID,MAX(LCOUNT) AS LCOUNT
    FROM
    (SELECT V372_CALLINGPARTYNUMBER AS MSISDN,V381_CALLINGCELLID, COUNT(V381_CALLINGCELLID) LCOUNT
    FROM L3_VOICE --PARTITION (VOICE_2346)
    WHERE V387_CHARGINGTIME_KEY = (SELECT DATE_KEY FROM DATE_DIM WHERE TRUNC(DATE_VALUE)=TRUNC(SYSDATE-1))
    and V378_SERVICEFLOW=1
    GROUP BY V372_CALLINGPARTYNUMBER,V381_CALLINGCELLID
    )
    GROUP BY MSISDN,V381_CALLINGCELLID;
    COMMIT;
END;
/

