--
-- MSISDN_COMPARE_2  (Procedure) 
--
CREATE OR REPLACE PROCEDURE DWH_USER.MSISDN_COMPARE_2 IS
    VDATE_KEY        VARCHAR2(12);
    VPERTITION       VARCHAR2(50);
BEGIN

    SELECT 'DATA_'||DATE_KEY INTO VPERTITION
    FROM DATE_DIM
    WHERE DATE_KEY = (SELECT A.DATE_KEY FROM DATE_DIM A WHERE A.DATE_VALUE = TO_DATE (SYSDATE,'dd/mm/rrrr'));
    
    SELECT DATE_KEY INTO VDATE_KEY 
    FROM DATE_DIM
    WHERE DATE_KEY = (SELECT A.DATE_KEY FROM DATE_DIM A WHERE A.DATE_VALUE = TO_DATE (SYSDATE-1,'dd/mm/rrrr'));
    
    INSERT INTO MSISDN_DATA_FOR_SYSDATE_1
    SELECT VDATE_KEY,MSISDN,SUBSTR(G379_CALLINGCELLID,16,30) AS G379_CALLINGCELLID,LCOUNT,G383_CHARGINGTIME_HOUR
    FROM
    (
    SELECT VDATE_KEY, A.MSISDN,LPAD(A.G379_CALLINGCELLID,30,0) AS G379_CALLINGCELLID, LCOUNT,B.G383_CHARGINGTIME_HOUR
    FROM MSISDN_DATA_FOR_SYSDATE_1_LD A, L3_DATA PARTITION (DATA_2345) B
    WHERE A.DATE_KEY =VDATE_KEY
    AND B.G383_CHARGINGTIME_KEY = VDATE_KEY--(SELECT DATE_KEY FROM DATE_DIM WHERE TRUNC(DATE_VALUE)=TRUNC(SYSDATE-1))
    AND A.MSISDN=B.G372_CALLINGPARTYNUMBER
    AND A.G379_CALLINGCELLID=B.G379_CALLINGCELLID
    GROUP BY A.MSISDN,A.G379_CALLINGCELLID,LCOUNT,B.G383_CHARGINGTIME_HOUR
    );
    COMMIT;
END;
/

