--
-- P_L1_TO_L3_ETSAF_OLD  (Procedure) 
--
CREATE OR REPLACE PROCEDURE DWH_USER.P_L1_TO_L3_ETSAF_OLD IS
    VDATE_KEY VARCHAR2(4);
BEGIN

--    EXECUTE IMMEDIATE'TRUNCATE TABLE L3_ETSAF DROP STORAGE';
    
    SELECT DATE_KEY INTO VDATE_KEY FROM DATE_DIM
    WHERE DATE_KEY = (SELECT DATE_KEY FROM DATE_DIM WHERE TRUNC(DATE_VALUE) = TRUNC(SYSDATE-1));
    
    INSERT INTO ETL_LOG@DWH05TODWH01 (LAYER, DATE_KEY, SOURCE, STATUS, FILE_COUNT, PER_COUNT, POST_COUNT, INSERT_TIME)
    VALUES              ('L3_ETSAF',VDATE_KEY,'etsaf','','','','',SYSDATE);
    COMMIT;
    
    INSERT INTO L3_ETSAF
    SELECT /*+ PARALLEL(S,16) */
    C.DATE_KEY AS ETL_DATE_KEY,
    MSISDN ,     
    TYPE ,       
    NID ,        
    DOB ,        
    TXN_NO ,     
    ICCID ,      
    ENTRY_DATE  ,
    LPAD(PROCESSED_BY,13,880) AS PROCESSED_BY,
    IMEI
    FROM  L1_ETSAF@DWH05TODWH01 S,DATE_DIM C
    WHERE TRUNC(PROCESSED_DATE)=TRUNC(SYSDATE)
    AND TO_DATE(C.DATE_VALUE,'DD/MM/YYYY')=TO_DATE(S.PROCESSED_DATE, 'DD/MM/YYYY');
    COMMIT;
    
    UPDATE ETL_LOG@DWH05TODWH01 SET STATUS = 96,
    UPDATE_TIME=SYSDATE
    WHERE DATE_KEY = VDATE_KEY
    AND LAYER = 'L3_ETSAF';        
    COMMIT;
EXCEPTION
 WHEN OTHERS THEN NULL;
END;
/

