--
-- P_L1_TO_L3_EVCREC  (Procedure) 
--
CREATE OR REPLACE PROCEDURE DWH_USER.P_L1_TO_L3_EVCREC (P_PROCESS_DATE VARCHAR2) IS
    VCOUNT NUMBER;
    VDATE_KEY VARCHAR2(4);
    VSTATUS NUMBER;
    VDATE DATE := TO_DATE(TO_DATE(P_PROCESS_DATE,'YYYYMMDD'),'DD/MM/RRRR');
BEGIN
    SELECT COUNT(*) INTO VCOUNT 
    FROM CDR_HEAD@DWH05TODWH02
    WHERE SOURCE = 'evcREC'
    AND PROCESS_STATUS = 96
    AND TO_DATE(PROCESS_DATE,'DD/MM/RRRR') = VDATE;
    
    SELECT DATE_KEY INTO VDATE_KEY FROM DATE_DIM
    WHERE DATE_KEY = (SELECT A.DATE_KEY FROM DATE_DIM A WHERE A.DATE_VALUE = VDATE);
    
  IF VCOUNT >= 1  THEN
      INSERT INTO ETL_LOG@DWH05TODWH02 (LAYER, DATE_KEY, SOURCE, STATUS, FILE_COUNT, PER_COUNT, POST_COUNT, INSERT_TIME)
      VALUES              ('L1_EVCREC',VDATE_KEY,'evcREC','96',VCOUNT,'','',SYSDATE);
      commit;
        
    SELECT STATUS INTO VSTATUS
    FROM ETL_LOG@DWH05TODWH02
    WHERE DATE_KEY = (SELECT A.DATE_KEY FROM DATE_DIM A WHERE A.DATE_VALUE = VDATE-1)
    AND LAYER = 'L3_EVCREC'
    AND SOURCE = 'evcREC';   
    
    IF VSTATUS = 96 THEN
        INSERT INTO ETL_LOG@DWH05TODWH02 (LAYER, DATE_KEY, SOURCE, STATUS, FILE_COUNT, PER_COUNT, POST_COUNT, INSERT_TIME)
        VALUES    ('L3_EVCREC',VDATE_KEY,'evcREC','30',VCOUNT,'','',SYSDATE);
        commit;
        
        INSERT INTO L3_EVCREC
        SELECT /*+ PARALLEL(S,8) */
        C.DATE_KEY AS ETL_DATE_KEY              ,    
        ER02_REGION_ID               ,
        '880'||ER03_MSISDN_DEALER           ,
        ER04_INITIATOR_DEALER_ID     ,
        ER05_INITIATOR_TEMPLATE_ID   ,
        ER06_DEALER_NAME             ,
        SUM(ER09_PRICE)                      ,
        '880'||ER10_MSISDN                  ,
        ER11_SUBSCRIBER_TYPE         ,
        B.DATE_KEY AS ER12_RECHARGE_DATE_KEY         ,
        SUBSTR(ER12_RECHARGE_DATE,9,4) AS ER12_RECHARGE_DATE_HOUR,
        ER13_SERIAL_NUMBER_CARD      ,
        ER14_RESPONSE_STATE          ,
        ER15_TRANSACTION_STATUS      ,
        ER16_ADJUST_STATUS           ,
        ER18_ACCESS_TYPE             ,
        SUM(ER19_DEALER_DECREASE_MONEY),
        SUM(ER20_ACCEPTOR_INCREASE_MONEY),
        ER21_COMMISSION_RATE_RECHARGE,
        ER22_SENDER_ID               ,
        SUM(ER24_BALANCE_STOCK_ADJUSTOR)     ,
        SUM(ER25_RECHARGE_HANDLING_FEE)      ,
        SUM(ER26_BALANCE_AFTER_RECHARGE)     ,
        ER31_FUNCTION_ID             ,
        SUM(ER34_NEW_BALANCE)                ,
        ER38_RECHARGE_DURATION       ,
        ER39_IN_RECHARGE_DURATION    ,
        '880'||ER40_UPSTREAM_MSISDN          ,
        ER41_UPSTREAM_NAME           
        FROM L1_EVCREC@DWH05TODWH02 S,DATE_DIM B,DATE_DIM C
        WHERE TO_DATE(B.DATE_VALUE,'DD/MM/YYYY')=TO_DATE(TO_DATE( SUBSTR(S.ER12_RECHARGE_DATE,1,8), 'YYYYMMDD'), 'DD/MM/YYYY')
        AND TO_DATE(C.DATE_VALUE,'DD/MM/YYYY')=TO_DATE(S.PROCESSED_DATE, 'DD/MM/YYYY')
        AND TO_DATE(S.PROCESSED_DATE,'DD/MM/RRRR') = VDATE
        GROUP BY
        C.DATE_KEY               ,    
        ER02_REGION_ID               ,
        '880'||ER03_MSISDN_DEALER           ,
        ER04_INITIATOR_DEALER_ID     ,
        ER05_INITIATOR_TEMPLATE_ID   ,
        ER06_DEALER_NAME             ,
        '880'||ER10_MSISDN                  ,
        ER11_SUBSCRIBER_TYPE         ,
        B.DATE_KEY ,
        SUBSTR(ER12_RECHARGE_DATE,9,4) ,
        ER13_SERIAL_NUMBER_CARD      ,
        ER14_RESPONSE_STATE          ,
        ER15_TRANSACTION_STATUS      ,
        ER16_ADJUST_STATUS           ,
        ER18_ACCESS_TYPE             ,
        ER21_COMMISSION_RATE_RECHARGE,
        ER22_SENDER_ID               ,
        ER31_FUNCTION_ID             ,
        ER38_RECHARGE_DURATION       ,
        ER39_IN_RECHARGE_DURATION    ,
        '880'||ER40_UPSTREAM_MSISDN          ,
        ER41_UPSTREAM_NAME;  
        COMMIT;
        UPDATE ETL_LOG@DWH05TODWH02 SET STATUS = 96 
        WHERE DATE_KEY = VDATE_KEY
        AND LAYER = 'L3_EVCREC';        
        COMMIT;
    END IF;
  ELSE
     INSERT INTO ETL_LOG@DWH05TODWH02 (LAYER, DATE_KEY, SOURCE, STATUS, FILE_COUNT, PER_COUNT, POST_COUNT, INSERT_TIME)
     VALUES              ('L1_EVCREC',VDATE_KEY,'evcREC','34',VCOUNT,'','',SYSDATE);
    COMMIT;
  END IF;
EXCEPTION
 WHEN OTHERS THEN NULL;
END;
/

