--
-- P_L1_TO_L3_SMSC  (Procedure) 
--
CREATE OR REPLACE PROCEDURE DWH_USER.P_L1_TO_L3_SMSC (P_PROCESS_DATE VARCHAR2) IS
    VCOUNT NUMBER;
    VDATE_KEY NUMBER;
    VSTATUS2 NUMBER;
    VDATE DATE := TO_DATE(TO_DATE(P_PROCESS_DATE,'YYYYMMDD'),'DD/MM/RRRR');
BEGIN
    SELECT COUNT(*) INTO VCOUNT 
    FROM CDR_HEAD@DWH05TODWH03
    WHERE SOURCE = 'smsc'
    AND PROCESS_STATUS = 96
    AND TRUNC(PROCESS_DATE) = TRUNC(VDATE);
    
    SELECT DATE_KEY INTO VDATE_KEY FROM DATE_DIM
    WHERE DATE_KEY = (SELECT DATE_KEY FROM DATE_DIM WHERE TRUNC(DATE_VALUE) = TRUNC(VDATE));
    
  IF VCOUNT > 0  THEN
      INSERT INTO ETL_LOG@DWH05TODWH03 (LAYER, DATE_KEY, SOURCE, STATUS, FILE_COUNT, PER_COUNT, POST_COUNT, INSERT_TIME)
      VALUES              ('L1_SMSC',VDATE_KEY,'smsc','96',VCOUNT,'','',SYSDATE);
      COMMIT;
    
    SELECT COUNT(STATUS) INTO VSTATUS2
    FROM ETL_LOG@DWH05TODWH03
    WHERE DATE_KEY = (SELECT A.DATE_KEY FROM DATE_DIM A WHERE TRUNC(DATE_VALUE) = TRUNC(VDATE))
    AND LAYER = 'L3_SMSC'
    AND SOURCE = 'smsc';   
    
    IF  VSTATUS2=0 THEN
        INSERT INTO ETL_LOG@DWH05TODWH03 (LAYER, DATE_KEY, SOURCE, STATUS, FILE_COUNT, PER_COUNT, POST_COUNT, INSERT_TIME)
        VALUES              ('L3_SMSC',VDATE_KEY,'smsc','30',VCOUNT,'','',SYSDATE);
        COMMIT;
        
        INSERT INTO L3_SMSC
        SELECT /*+ parallel (A,16) */ B.DATE_KEY,C.DATE_KEY, SMC2_SM_ID,SMC6_DESTINATION_DELIVERY_A, SMC15_SMSTATUS, SMC16_ERROR_CODE, SMC27_MTMSCADDR,SMC30_ORGACCOUNT
        FROM
        (
        SELECT /*+ parallel (A,16) */ PROCESSED_DATE, SMC2_SM_ID, SMC15_SMSTATUS ,SMC30_ORGACCOUNT, LPAD(SMC6_DESTINATION_DELIVERY_A,13,880) SMC6_DESTINATION_DELIVERY_A,LPAD(SMC27_MTMSCADDR,13,880)SMC27_MTMSCADDR,SMC16_ERROR_CODE ,MAX(SMC1_TIME_SERIAL_NUMBER)AS SMC1_TIME_SERIAL_NUMBER
        FROM L1_SMSC@DWH05TODWH03 A
        WHERE TRUNC(A.PROCESSED_DATE)= TRUNC(VDATE)
        GROUP BY PROCESSED_DATE,SMC2_SM_ID, SMC15_SMSTATUS ,SMC30_ORGACCOUNT, LPAD(SMC6_DESTINATION_DELIVERY_A,13,880),LPAD(SMC27_MTMSCADDR,13,880) ,SMC16_ERROR_CODE
        ) A, DATE_DIM B, DATE_DIM C
        WHERE TRUNC(B.DATE_VALUE)=TRUNC(A.PROCESSED_DATE)
        AND TO_CHAR(C.DATE_VALUE,'RRRRMMDD')=SUBSTR(A.SMC1_TIME_SERIAL_NUMBER,1,8);
        COMMIT;
        
        UPDATE ETL_LOG@DWH05TODWH03 SET STATUS = 96,
        UPDATE_TIME=SYSDATE
        WHERE DATE_KEY = VDATE_KEY
        AND LAYER = 'L3_SMSC';        
        COMMIT;
    END IF;
  ELSE
     INSERT INTO ETL_LOG@DWH05TODWH03 (LAYER, DATE_KEY, SOURCE, STATUS, FILE_COUNT, PER_COUNT, POST_COUNT, INSERT_TIME)
     VALUES              ('L3_SMSC',VDATE_KEY,'smsc','34',VCOUNT,'','',SYSDATE);
    COMMIT;
  END IF;
EXCEPTION
 WHEN OTHERS THEN NULL;
END;
/

