--
-- P_L1_TO_L3_ETSAF  (Procedure) 
--
CREATE OR REPLACE PROCEDURE DWH_USER.P_L1_TO_L3_ETSAF IS
    VDATE_KEY VARCHAR2(4);
    VPRE_COUNT NUMBER;
    VCOUNT NUMBER;
BEGIN

    
    SELECT DATE_KEY INTO VDATE_KEY FROM DATE_DIM
    WHERE DATE_KEY = (SELECT DATE_KEY FROM DATE_DIM WHERE TRUNC(DATE_VALUE) = TRUNC(SYSDATE-1));
    
    SELECT COUNT(*) INTO VPRE_COUNT
    FROM L1_ETSAF@DWH05TODWH01
    WHERE TRUNC(PROCESSED_DATE)=TRUNC(SYSDATE-1);
    
    IF VPRE_COUNT > 0 THEN
    
        INSERT INTO ETL_LOG@DWH05TODWH01 (LAYER, DATE_KEY, SOURCE, STATUS, FILE_COUNT, PER_COUNT, POST_COUNT, INSERT_TIME)
        VALUES                           ('L1_ETSAF',VDATE_KEY,'etsaf',96,'',VPRE_COUNT,'',SYSDATE);
        COMMIT;

        SELECT COUNT(*) INTO VCOUNT
        FROM ETL_LOG@DWH05TODWH01 
        WHERE DATE_KEY=VDATE_KEY
        AND LAYER='L3_ETSAF'
        AND STATUS=96;  
               
        IF VCOUNT=0 THEN
        
            INSERT INTO ETL_LOG@DWH05TODWH01 (LAYER, DATE_KEY, SOURCE, STATUS, FILE_COUNT, PER_COUNT, POST_COUNT, INSERT_TIME)
            VALUES              ('L3_ETSAF',VDATE_KEY,'etsaf',30,'','','',SYSDATE);
            COMMIT;
                
            INSERT INTO L3_ETSAF
            SELECT /*+ PARALLEL(S,16) */ C.DATE_KEY AS ETL_DATE_KEY,SAF02_MSISDN,SAF33_REG_TYPE_DESC,SAF03_NID,SAF05_DOB,SAF25_TXN,SAF28_ICCID,TO_DATE(TO_CHAR(SAF22_ENTRYDATE,'RRRR/MM/DD'),'RRRR/MM/DD') as SAF22_ENTRYDATE,LPAD(SAF19_SALESMAN,13,880) AS PROCESSED_BY,SAF23_IPADDRESS
            FROM  L1_ETSAF@DWH05TODWH01 S,DATE_DIM C
            WHERE TRUNC(S.PROCESSED_DATE)=TRUNC(SYSDATE-1)
            AND TRUNC(C.DATE_VALUE)=TRUNC(S.PROCESSED_DATE);
            COMMIT;
            
            UPDATE ETL_LOG@DWH05TODWH01 SET STATUS = 96,
            UPDATE_TIME=SYSDATE
            WHERE DATE_KEY = VDATE_KEY
            AND LAYER = 'L3_ETSAF';        
            COMMIT;
          ELSE
            INSERT INTO ETL_LOG@DWH05TODWH01 (LAYER, DATE_KEY, SOURCE, STATUS, FILE_COUNT, PER_COUNT, POST_COUNT, INSERT_TIME)
            VALUES              ('L3_ETSAF',VDATE_KEY,'etsaf',34,'','','',SYSDATE);
            COMMIT;
          END IF;
    ELSE
        INSERT INTO ETL_LOG@DWH05TODWH01 (LAYER, DATE_KEY, SOURCE, STATUS, FILE_COUNT, PER_COUNT, POST_COUNT, INSERT_TIME)
        VALUES                           ('L1_ETSAF',VDATE_KEY,'etsaf','34','',VPRE_COUNT,'',SYSDATE);
        COMMIT;
    END IF;

END;
/

