--
-- P_L1_TO_L3_EVCTRA  (Procedure) 
--
CREATE OR REPLACE PROCEDURE DWH_USER.P_L1_TO_L3_EVCTRA (P_PROCESS_DATE VARCHAR2) IS
    VCOUNT NUMBER;
    VDATE_KEY NUMBER;
    VSTATUS NUMBER;
    VDATE DATE := TO_DATE(TO_DATE(P_PROCESS_DATE,'YYYYMMDD'),'DD/MM/RRRR');
BEGIN
    SELECT COUNT(*) INTO VCOUNT 
    FROM CDR_HEAD@DWH05TODWH02
    WHERE SOURCE = 'evcTRA'
    AND PROCESS_STATUS = 96
    AND TO_DATE(PROCESS_DATE,'DD/MM/RRRR') = VDATE;
    
    SELECT DATE_KEY INTO VDATE_KEY FROM DATE_DIM
    WHERE DATE_KEY = (SELECT A.DATE_KEY FROM DATE_DIM A WHERE A.DATE_VALUE = VDATE);
    
  IF VCOUNT >= 1  THEN
      INSERT INTO ETL_LOG@DWH05TODWH02 (LAYER, DATE_KEY, SOURCE, STATUS, FILE_COUNT, PER_COUNT, POST_COUNT, INSERT_TIME)
    VALUES              ('L1_EVCTRA',VDATE_KEY,'evcTRA','96',VCOUNT,'','',SYSDATE);
    commit;
    
    SELECT STATUS INTO VSTATUS
    FROM ETL_LOG@DWH05TODWH02
    WHERE DATE_KEY = (SELECT A.DATE_KEY FROM DATE_DIM A WHERE A.DATE_VALUE = VDATE-1)
    AND LAYER = 'L3_EVCTRA'
    AND SOURCE = 'evcTRA';   
    
    IF VSTATUS = 96 THEN
        INSERT INTO ETL_LOG@DWH05TODWH02 (LAYER, DATE_KEY, SOURCE, STATUS, FILE_COUNT, PER_COUNT, POST_COUNT, INSERT_TIME)
        VALUES    ('L3_EVCTRA',VDATE_KEY,'evcTRA','30',VCOUNT,'','',SYSDATE);
        
        INSERT INTO L3_EVCTRA
        SELECT /*+ PARALLEL(S,8) */
        C.DATE_KEY AS ETL_DATE_KEY                  ,
        ET02_REGION_ID               ,
        '880'||ET03_MSISDN_DEALER                ,
        ET04_INITIATOR_ID            ,
        ET05_DEALER_NAME             ,
        '880'||ET06_MSISDN_BENEFICIARY           ,
        ET07_RECIPIENT_ID            ,
        ET08_DEALER_NAME             ,
        ET09_PRICE_TYPE              ,
        SUM(ET10_AMOUNT_ROLLBACK)                ,
        ET11_SENDER_TRANSACTION      ,
        B.DATE_KEY AS ET12_TRANSFER_DATE_KEY    ,
        SUBSTR(ET12_TRANSFER_DATE,9,4) AS ET12_TRANSFER_HOUR,
        ET13_STATE                   ,
        ET15_ACCESS_TYPE             ,
        SUM(ET16_DEALER_DECREASE_MONEY)   ,
        SUM(ET17_ACCEPTOR_INCREASE_MONEY) ,
        SUM(ET18_TRANSFER_COMMISSION_RATE),
        ET19_SENDER_TEMPLATE_ID      ,
        ET20_RECEIVER_TEMPLATE_ID    ,
        SUM(ET21_SENDER_BALANCE_STOCK_ADJ)   ,
        SUM(ET22_TRANSFER_HANDLING_FEE)           ,
        ET23_TAX                     ,
        SUM(ET24_RECEIVER_AFTER_ADJUSTOR) ,
        SUM(ET25_RECEIVER_BEFORE_ADJUSTOR),
        ET30_QUANTITY                ,
        SUM(ET32_ACTUAL_PAYMENT_AMOUNT) / 1000000
        FROM L1_EVCTRA@DWH05TODWH02 S,DATE_DIM B,DATE_DIM C
        WHERE TO_DATE(B.DATE_VALUE,'DD/MM/YYYY')=TO_DATE(TO_DATE( SUBSTR(S.ET12_TRANSFER_DATE,1,8), 'YYYYMMDD'), 'DD/MM/YYYY')
        AND TO_DATE(C.DATE_VALUE,'DD/MM/YYYY')=TO_DATE(S.PROCESSED_DATE, 'DD/MM/YYYY')
        AND TO_DATE(S.PROCESSED_DATE,'DD/MM/RRRR') = VDATE
        GROUP BY
        C.DATE_KEY                  ,
        ET02_REGION_ID               ,
        '880'||ET03_MSISDN_DEALER                ,
        ET04_INITIATOR_ID            ,
        ET05_DEALER_NAME             ,
        '880'||ET06_MSISDN_BENEFICIARY           ,
        ET07_RECIPIENT_ID            ,
        ET08_DEALER_NAME             ,
        ET09_PRICE_TYPE              ,
        ET11_SENDER_TRANSACTION      ,
        B.DATE_KEY                      ,
        SUBSTR(ET12_TRANSFER_DATE,9,4),
        ET13_STATE                   ,
        ET15_ACCESS_TYPE             ,
        ET19_SENDER_TEMPLATE_ID      ,
        ET20_RECEIVER_TEMPLATE_ID    ,
        ET23_TAX                     ,
        ET30_QUANTITY; 
        COMMIT;          
        UPDATE ETL_LOG@DWH05TODWH02 SET STATUS = 96 
        WHERE DATE_KEY = VDATE_KEY
        AND LAYER = 'L3_EVCTRA';        
        COMMIT;
    END IF;
  ELSE
     INSERT INTO ETL_LOG@DWH05TODWH02 (LAYER, DATE_KEY, SOURCE, STATUS, FILE_COUNT, PER_COUNT, POST_COUNT, INSERT_TIME)
     VALUES              ('L1_EVCTRA',VDATE_KEY,'evcTRA','34',VCOUNT,'','',SYSDATE);
    COMMIT;
  END IF;
EXCEPTION
 WHEN OTHERS THEN NULL;
END;
/

