--
-- P_L1_TO_L3_CGW  (Procedure) 
--
CREATE OR REPLACE PROCEDURE DWH_USER.P_L1_TO_L3_CGW (P_PROCESS_DATE VARCHAR2) IS
    VCOUNT NUMBER;
    VDATE_KEY NUMBER;
    VSTATUS2 NUMBER;
    VDATE DATE := TO_DATE(TO_DATE(P_PROCESS_DATE,'YYYYMMDD'),'DD/MM/RRRR');
BEGIN
    SELECT COUNT(*) INTO VCOUNT 
    FROM CDR_HEAD@DWH05TODWH03
    WHERE SOURCE = 'cgw'
    AND PROCESS_STATUS = 96
    AND TO_DATE(PROCESS_DATE,'DD/MM/RRRR') = VDATE;
    
    SELECT DATE_KEY INTO VDATE_KEY FROM DATE_DIM
    WHERE DATE_KEY = (SELECT A.DATE_KEY FROM DATE_DIM A WHERE A.DATE_VALUE = VDATE);
    
  IF VCOUNT >= 1  THEN
      INSERT INTO ETL_LOG@DWH05TODWH03 (LAYER, DATE_KEY, SOURCE, STATUS, FILE_COUNT, PER_COUNT, POST_COUNT, INSERT_TIME)
      VALUES              ('L1_CGW',VDATE_KEY,'cgw','96',VCOUNT,'','',SYSDATE);
      COMMIT;
       

    
    SELECT COUNT(STATUS) INTO VSTATUS2
    FROM ETL_LOG@DWH05TODWH03
    WHERE DATE_KEY = (SELECT A.DATE_KEY FROM DATE_DIM A WHERE A.DATE_VALUE = VDATE)
    AND LAYER = 'L3_CGW'
    AND SOURCE = 'cgw';   
    
    IF  VSTATUS2=0 THEN
        INSERT INTO ETL_LOG@DWH05TODWH03 (LAYER, DATE_KEY, SOURCE, STATUS, FILE_COUNT, PER_COUNT, POST_COUNT, INSERT_TIME)
        VALUES              ('L3_CGW',VDATE_KEY,'cgw','30',VCOUNT,'','',SYSDATE);
        COMMIT;
        INSERT INTO L3_CGW
        SELECT /*+ PARALLEL(A,16) */
        B.DATE_KEY AS ETL_DATE_KEY,
        CGW1_ID                ,
        CGW2_GLOBAL_ID         ,
        CGW3_TID               ,
        CGW4_USER_ID           ,
        CGW5_USERNAME          ,
        CGW6_OPERATION         ,
        CGW7_MSISDN            ,
        CGW8_PREPAID           ,
        CGW10_RESULT_CODE      ,
        CGW11_RESULT_DESC      ,
        CGW12_CURRENT_BALANCE  ,
        CGW13_PREVIOUS_BALANCE ,
        CGW14_AMOUNT/100           ,
        C.DATE_KEY AS CGW15_TRANSACTION_TIME_KEY
        FROM L1_CGW@DWH05TODWH03 A,DATE_DIM B,DATE_DIM C
        WHERE TO_DATE(PROCESSED_DATE)= VDATE
        AND TO_DATE(B.DATE_VALUE,'DD/MM/YYYY')=TO_DATE(A.PROCESSED_DATE, 'DD/MM/YYYY')
        AND TO_CHAR(C.DATE_VALUE,'RRRRMMDD')=SUBSTR(CGW15_TRANSACTION_TIME,1,8);
        COMMIT;
    UPDATE ETL_LOG@DWH05TODWH03 SET STATUS = 96,
    UPDATE_TIME=SYSDATE
    WHERE DATE_KEY = VDATE_KEY
    AND LAYER = 'L3_CGW';        
        COMMIT;
    END IF;
  ELSE
     INSERT INTO ETL_LOG@DWH05TODWH03 (LAYER, DATE_KEY, SOURCE, STATUS, FILE_COUNT, PER_COUNT, POST_COUNT, INSERT_TIME)
     VALUES              ('L3_CGW',VDATE_KEY,'cgw','34',VCOUNT,'','',SYSDATE);
    COMMIT;
  END IF;
EXCEPTION
 WHEN OTHERS THEN NULL;
END;
/

