--
-- P_L2_TO_L3_RECURRING_MANUAL  (Procedure) 
--
CREATE OR REPLACE PROCEDURE DWH_USER.P_L2_TO_L3_RECURRING_MANUAL (P_PROCESS_DATE VARCHAR2) IS
    VCOUNT NUMBER;
    VDATE_KEY NUMBER;
    VL2STATUS NUMBER;
    VL3STATUS NUMBER;
    VDATE DATE := TO_DATE(TO_DATE(P_PROCESS_DATE,'YYYYMMDD'),'DD/MM/RRRR');
BEGIN    
    SELECT DATE_KEY INTO VDATE_KEY 
    FROM DATE_DIM
    WHERE DATE_KEY = (SELECT A.DATE_KEY FROM DATE_DIM A WHERE A.DATE_VALUE = VDATE);
    
    INSERT INTO L3_RECURRING
    SELECT /*+ PARALLEL(L2_RECURRING,16) */
    ETL_DATE_KEY                ,
    R41_DEBIT_AMOUNT          ,
    R373_MAINOFFERINGID       ,
    R374_PAYTYPE              ,
    R375_CHARGINGPARTYNUMBER  ,
    R377_CYCLEBEGINTIME_KEY   ,
    R377_CYCLEBEGINTIME_HOUR  ,
    R379_CYCLETYPE            ,
    R384_PRODUCTID            ,
    R385_OFFERINGID,
    R386_OFFERINGINSTID       ,
    R387_ORDERSTATUS          ,
    R392_TRIGGERMODE          ,
    R394_PRODUCTCODE          ,
    R395_MAINBALANCEINFO      ,
    R402_TAXINFO              ,
    R408_PREPAID_BALANCE     ,
    R419_CALLINGNETWORKTYPE   ,
    R420_LOCALAREA            ,
    R421_BUNDLEPACKAGE        
    FROM L2_RECURRING@DWH05TODWH01
    WHERE ETL_DATE_KEY= VDATE_KEY;
    COMMIT;
    /*
    ETL_DATE_KEY                ,
    SUM(R41_DEBIT_AMOUNT)          ,
    R373_MAINOFFERINGID       ,
    R374_PAYTYPE              ,
    R375_CHARGINGPARTYNUMBER  ,
    R377_CYCLEBEGINTIME_KEY   ,
    R377_CYCLEBEGINTIME_HOUR  ,
    R379_CYCLETYPE            ,
    R384_PRODUCTID            ,
    R385_OFFERINGID,
    R386_OFFERINGINSTID       ,
    R387_ORDERSTATUS          ,
    R392_TRIGGERMODE          ,
    R394_PRODUCTCODE          ,
    R395_MAINBALANCEINFO      ,
    R402_TAXINFO              ,
    SUM(R408_PREPAID_BALANCE)      ,
    R419_CALLINGNETWORKTYPE   ,
    R420_LOCALAREA            ,
    R421_BUNDLEPACKAGE        
    FROM L2_RECURRING@DWH05TODWH01
    WHERE ETL_DATE_KEY= VDATE_KEY
    GROUP BY 
    ETL_DATE_KEY                ,
    R373_MAINOFFERINGID       ,
    R374_PAYTYPE              ,
    R375_CHARGINGPARTYNUMBER  ,
    R377_CYCLEBEGINTIME_KEY   ,
    R377_CYCLEBEGINTIME_HOUR   ,
    R379_CYCLETYPE            ,
    R384_PRODUCTID            ,
     R385_OFFERINGID,
    R386_OFFERINGINSTID       ,
    R387_ORDERSTATUS          ,
    R392_TRIGGERMODE          ,
    R394_PRODUCTCODE          ,
    R395_MAINBALANCEINFO      ,
    R402_TAXINFO              ,
    R419_CALLINGNETWORKTYPE   ,
    R420_LOCALAREA            ,
    R421_BUNDLEPACKAGE;   
    COMMIT;  
    */
    INSERT INTO ETL_LOG@DWH05TODWH01 (LAYER, DATE_KEY, SOURCE, STATUS, FILE_COUNT, PER_COUNT, POST_COUNT, INSERT_TIME)
    VALUES              ('L3_RECURRING',VDATE_KEY,'mon','96','','','',SYSDATE);
    COMMIT;      
EXCEPTION
 WHEN OTHERS THEN NULL;
END;
/

