--
-- P_L2_TO_L3_RECURRING  (Procedure) 
--
CREATE OR REPLACE PROCEDURE DWH_USER.P_L2_TO_L3_RECURRING (P_PROCESS_DATE VARCHAR2) IS
    VCOUNT NUMBER;
    VDATE_KEY NUMBER;
    VL2STATUS NUMBER;
    VL3STATUS NUMBER;
    VDATE DATE := TO_DATE(TO_DATE(P_PROCESS_DATE,'YYYYMMDD'),'DD/MM/RRRR');
BEGIN
    SELECT COUNT(STATUS) INTO VL3STATUS
    FROM ETL_LOG@DWH05TODWH01
    WHERE DATE_KEY = (SELECT A.DATE_KEY FROM DATE_DIM A WHERE A.DATE_VALUE = VDATE)
    AND LAYER = 'L3_RECURRING'
    AND SOURCE = 'mon'
    AND STATUS = 96 ; 
    
    SELECT DATE_KEY INTO VDATE_KEY 
    FROM DATE_DIM@DWH05TODWH01
    WHERE DATE_KEY = (SELECT A.DATE_KEY FROM DATE_DIM A WHERE A.DATE_VALUE = VDATE);--(SELECT A.DATE_KEY FROM DATE_DIM A WHERE TO_DATE(A.DATE_VALUE,'DD/MM/YYYY') = TO_DATE(SYSDATE,'DD/MM/YYYY'));
        
    SELECT STATUS INTO VL2STATUS
    FROM ETL_LOG@DWH05TODWH01
    WHERE DATE_KEY = (SELECT A.DATE_KEY FROM DATE_DIM A WHERE A.DATE_VALUE = VDATE)
    AND LAYER = 'L2_RECURRING'
    AND SOURCE = 'mon';  
    
      
   IF VL3STATUS = 0 THEN   
   
       IF VL2STATUS = 96 THEN
        INSERT INTO ETL_LOG@DWH05TODWH01 (LAYER, DATE_KEY, SOURCE, STATUS, FILE_COUNT, PER_COUNT, POST_COUNT, INSERT_TIME)
        VALUES              ('L3_RECURRING',VDATE_KEY,'mon','30','','','',SYSDATE);
        COMMIT;
        
        INSERT INTO L3_RECURRING
        SELECT /*+ PARALLEL(L2_RECURRING,16) */
        ETL_DATE_KEY                ,
        R41_DEBIT_AMOUNT          ,
        R373_MAINOFFERINGID       ,
        R374_PAYTYPE              ,
        R375_CHARGINGPARTYNUMBER  ,
        R377_CYCLEBEGINTIME_KEY   ,
        R377_CYCLEBEGINTIME_HOUR  ,
        R379_CYCLETYPE            ,
        R384_PRODUCTID            ,
        R385_OFFERINGID,
        R386_OFFERINGINSTID       ,
        R387_ORDERSTATUS          ,
        R392_TRIGGERMODE          ,
        R394_PRODUCTCODE          ,
        R395_MAINBALANCEINFO      ,
        R402_TAXINFO              ,
        R408_PREPAID_BALANCE     ,
        R419_CALLINGNETWORKTYPE   ,
        R420_LOCALAREA            ,
        R421_BUNDLEPACKAGE        ,
        COUNT(ETL_DATE_KEY)        
        FROM L2_RECURRING@DWH05TODWH01
        WHERE ETL_DATE_KEY= VDATE_KEY
        GROUP BY 
        ETL_DATE_KEY                ,
        R41_DEBIT_AMOUNT          ,
        R373_MAINOFFERINGID       ,
        R374_PAYTYPE              ,
        R375_CHARGINGPARTYNUMBER  ,
        R377_CYCLEBEGINTIME_KEY   ,
        R377_CYCLEBEGINTIME_HOUR  ,
        R379_CYCLETYPE            ,
        R384_PRODUCTID            ,
        R385_OFFERINGID,
        R386_OFFERINGINSTID       ,
        R387_ORDERSTATUS          ,
        R392_TRIGGERMODE          ,
        R394_PRODUCTCODE          ,
        R395_MAINBALANCEINFO      ,
        R402_TAXINFO              ,
        R408_PREPAID_BALANCE     ,
        R419_CALLINGNETWORKTYPE   ,
        R420_LOCALAREA            ,
        R421_BUNDLEPACKAGE        ;
        COMMIT;
        
        UPDATE ETL_LOG@DWH05TODWH01 SET STATUS = 96,
        UPDATE_TIME=SYSDATE
        WHERE DATE_KEY = VDATE_KEY
        AND LAYER = 'L3_RECURRING';        
        COMMIT;
    END IF;
  ELSE
     INSERT INTO ETL_LOG@DWH05TODWH01 (LAYER, DATE_KEY, SOURCE, STATUS, INSERT_TIME)
     VALUES              ('L3_RECURRING',VDATE_KEY,'mon','34',SYSDATE);
    COMMIT;
    END IF;
EXCEPTION
 WHEN OTHERS THEN NULL;
END;
/

