--
-- P_L2_TO_L3_MANAGEMENT_MANUAL  (Procedure) 
--
CREATE OR REPLACE PROCEDURE DWH_USER.P_L2_TO_L3_MANAGEMENT_MANUAL (P_PROCESS_DATE VARCHAR2) IS
    VCOUNT NUMBER;
    --VCOUNT NUMBER;
    VDATE_KEY NUMBER;
    VL2STATUS NUMBER;
    VL3STATUS NUMBER;
    VDATE DATE := TO_DATE(TO_DATE(P_PROCESS_DATE,'YYYYMMDD'),'DD/MM/RRRR');
BEGIN
    SELECT DATE_KEY INTO VDATE_KEY 
    FROM DATE_DIM@DWH05TODWH01
    WHERE DATE_KEY = (SELECT A.DATE_KEY FROM DATE_DIM A WHERE A.DATE_VALUE = VDATE);--(SELECT A.DATE_KEY FROM DATE_DIM A WHERE TO_DATE(A.DATE_VALUE,'DD/MM/YYYY') = TO_DATE(SYSDATE,'DD/MM/YYYY'));

        INSERT INTO L3_MANAGEMENT
        SELECT /*+ PARALLEL(L2_MANAGEMENT,16) */
        ETL_DATE_KEY                  ,
        M4_SPLIT_CDR_REASON           ,
        M9_STATUS                     ,
        M18_OBJ_TYPE                  ,
        M22_PRI_IDENTITY              ,
        M24_SERVICE_CATEGORY          ,
        M25_USAGE_SERVICE_TYPE        ,
        sum(M41_DEBIT_AMOUNT),
        M372_CALLINGPARTYNUMBER       ,
        M374_OPERATIONTYPE            ,
        M376_MAINOFFERINGID           ,
        M377_PAYTYPE                  ,
        M378_STARTTIMEOFBILLCYCLE_KEY   ,
        M378_STARTTIMEOFBILLCYCLE_HOUR  ,
        M385_USERSTATE                ,
        M399_CHARGEPARTYINDICATOR     ,
        M401_TAXINFO                  ,
        SUM( M402_PREPAID_BALANCE   )       ,
        SUM(M403_POSTPAID_BALANCE)
        FROM L2_MANAGEMENT@DWH05TODWH01
        WHERE ETL_DATE_KEY= VDATE_KEY
        GROUP BY  
        ETL_DATE_KEY                  ,
        M4_SPLIT_CDR_REASON           ,
        M9_STATUS                     ,
        M18_OBJ_TYPE                  ,
        M22_PRI_IDENTITY              ,
        M24_SERVICE_CATEGORY          ,
        M25_USAGE_SERVICE_TYPE        ,
        M372_CALLINGPARTYNUMBER       ,
        M374_OPERATIONTYPE            ,
        M376_MAINOFFERINGID           ,
        M377_PAYTYPE                  ,
        M378_STARTTIMEOFBILLCYCLE_KEY   ,
        M378_STARTTIMEOFBILLCYCLE_HOUR  ,
        M385_USERSTATE                ,
        M399_CHARGEPARTYINDICATOR     ,
        M401_TAXINFO;
        COMMIT;
        INSERT INTO ETL_LOG@DWH05TODWH01 (LAYER, DATE_KEY, SOURCE, STATUS, FILE_COUNT, PER_COUNT, POST_COUNT, INSERT_TIME)
        VALUES              ('L3_MANAGEMENT',VDATE_KEY,'cm','96','','','',SYSDATE);
EXCEPTION
 WHEN OTHERS THEN NULL;
END;
/

