--
-- P_L2_TO_L3_MANAGEMENT  (Procedure) 
--
CREATE OR REPLACE PROCEDURE DWH_USER.P_L2_TO_L3_MANAGEMENT (P_PROCESS_DATE VARCHAR2) IS
    VCOUNT NUMBER;
    VCOUNT NUMBER;
    VDATE_KEY NUMBER;
    VL2STATUS NUMBER;
    VL3STATUS NUMBER;
    VDATE DATE := TO_DATE(TO_DATE(P_PROCESS_DATE,'YYYYMMDD'),'DD/MM/RRRR');
BEGIN
    SELECT COUNT(STATUS) INTO VL3STATUS
    FROM ETL_LOG@DWH05TODWH01
    WHERE DATE_KEY = (SELECT A.DATE_KEY FROM DATE_DIM A WHERE A.DATE_VALUE = VDATE)
    AND LAYER = 'L3_MANAGEMENT'
    AND SOURCE = 'cm'
    AND STATUS = 96 ; 
    
    SELECT DATE_KEY INTO VDATE_KEY 
    FROM DATE_DIM@DWH05TODWH01
    WHERE DATE_KEY = (SELECT A.DATE_KEY FROM DATE_DIM A WHERE A.DATE_VALUE = VDATE);--(SELECT A.DATE_KEY FROM DATE_DIM A WHERE TO_DATE(A.DATE_VALUE,'DD/MM/YYYY') = TO_DATE(SYSDATE,'DD/MM/YYYY'));
        
    SELECT STATUS INTO VL2STATUS
    FROM ETL_LOG@DWH05TODWH01
    WHERE DATE_KEY = (SELECT A.DATE_KEY FROM DATE_DIM A WHERE A.DATE_VALUE = VDATE)
    AND LAYER = 'L2_MANAGEMENT'
    AND SOURCE = 'cm';  
    
      
   IF VL3STATUS = 0 THEN   
   
       IF VL2STATUS = 96 THEN
        INSERT INTO ETL_LOG@DWH05TODWH01 (LAYER, DATE_KEY, SOURCE, STATUS, FILE_COUNT, PER_COUNT, POST_COUNT, INSERT_TIME)
        VALUES              ('L3_MANAGEMENT',VDATE_KEY,'cm','30','','','',SYSDATE);
        COMMIT;
        
        INSERT INTO L3_MANAGEMENT
        SELECT /*+ PARALLEL(L2_MANAGEMENT,8) */
        ETL_DATE_KEY                  ,
        M4_SPLIT_CDR_REASON           ,
        M9_STATUS                     ,
        M18_OBJ_TYPE                  ,
        M22_PRI_IDENTITY              ,
        M24_SERVICE_CATEGORY          ,
        M25_USAGE_SERVICE_TYPE        ,
        sum(M41_DEBIT_AMOUNT),
        M372_CALLINGPARTYNUMBER       ,
        M374_OPERATIONTYPE            ,
        M376_MAINOFFERINGID           ,
        M377_PAYTYPE                  ,
        M378_STARTTIMEOFBILLCYCLE_KEY   ,
        M378_STARTTIMEOFBILLCYCLE_HOUR  ,
        M385_USERSTATE                ,
        M399_CHARGEPARTYINDICATOR     ,
        M401_TAXINFO                  ,
        SUM( M402_PREPAID_BALANCE   )       ,
        SUM(M403_POSTPAID_BALANCE)  ,
        COUNT(ETL_DATE_KEY)
        FROM L2_MANAGEMENT@DWH05TODWH01
        WHERE ETL_DATE_KEY= VDATE_KEY
        GROUP BY  
        ETL_DATE_KEY                  ,
        M4_SPLIT_CDR_REASON           ,
        M9_STATUS                     ,
        M18_OBJ_TYPE                  ,
        M22_PRI_IDENTITY              ,
        M24_SERVICE_CATEGORY          ,
        M25_USAGE_SERVICE_TYPE        ,
        M372_CALLINGPARTYNUMBER       ,
        M374_OPERATIONTYPE            ,
        M376_MAINOFFERINGID           ,
        M377_PAYTYPE                  ,
        M378_STARTTIMEOFBILLCYCLE_KEY   ,
        M378_STARTTIMEOFBILLCYCLE_HOUR  ,
        M385_USERSTATE                ,
        M399_CHARGEPARTYINDICATOR     ,
        M401_TAXINFO;
        COMMIT;
        UPDATE ETL_LOG@DWH05TODWH01 SET STATUS = 96,
        UPDATE_TIME=SYSDATE
        WHERE DATE_KEY = VDATE_KEY
        AND LAYER = 'L3_MANAGEMENT';        
        COMMIT;
    END IF;
  ELSE
     INSERT INTO ETL_LOG@DWH05TODWH01 (LAYER, DATE_KEY, SOURCE, STATUS, INSERT_TIME)
     VALUES              ('L3_MANAGEMENT',VDATE_KEY,'cm','34',SYSDATE);
    COMMIT;
    END IF;
EXCEPTION
 WHEN OTHERS THEN NULL;
END;
/

