--
-- P_L2_TO_L3_DATA  (Procedure) 
--
CREATE OR REPLACE PROCEDURE DWH_USER.P_L2_TO_L3_DATA (P_PROCESS_DATE VARCHAR2) IS
    VCOUNT NUMBER;
    VDATE_KEY NUMBER;
    VL2STATUS NUMBER;
    VL3STATUS NUMBER;
    VDATE DATE := TO_DATE(TO_DATE(P_PROCESS_DATE,'YYYYMMDD'),'DD/MM/RRRR');
BEGIN
    SELECT COUNT(STATUS) INTO VL3STATUS
    FROM ETL_LOG@DWH05TODWH01
    WHERE DATE_KEY = (SELECT A.DATE_KEY FROM DATE_DIM A WHERE A.DATE_VALUE = VDATE)
    AND LAYER = 'L3_DATA'
    AND SOURCE = 'data'
    AND STATUS = 96 ; 
    
    SELECT DATE_KEY INTO VDATE_KEY 
    FROM DATE_DIM@DWH05TODWH01
    WHERE DATE_KEY = (SELECT A.DATE_KEY FROM DATE_DIM A WHERE A.DATE_VALUE = VDATE);
    
    SELECT STATUS INTO VL2STATUS
    FROM ETL_LOG@DWH05TODWH01
    WHERE DATE_KEY = (SELECT A.DATE_KEY FROM DATE_DIM A WHERE A.DATE_VALUE = VDATE)
    AND LAYER = 'L2_DATA'
    AND SOURCE = 'data';      
      
   IF VL3STATUS = 0 THEN   
   
       IF VL2STATUS = 96 THEN
        INSERT INTO ETL_LOG@DWH05TODWH01 (LAYER, DATE_KEY, SOURCE, STATUS, FILE_COUNT, PER_COUNT, POST_COUNT, INSERT_TIME)
        VALUES              ('L3_DATA',VDATE_KEY,'data','30','','','',SYSDATE);
        COMMIT;
        
        INSERT INTO L3_DATA
        SELECT /*+ PARALLEL(L2_DATA,8) */
        ETL_DATE_KEY                  ,
        SUM(G41_DEBIT_AMOUNT)              ,
        SUM(G51_FREE_UNIT_AMOUNT_OF_FLUX)  ,
        G372_CALLINGPARTYNUMBER       ,
        G375_CALLINGPARTYIMSI         ,
        G379_CALLINGCELLID            ,
        G383_CHARGINGTIME_KEY         ,
        SUM(G384_TOTALFLUX)                ,
        G389_SERVICEID                ,
        G401_MAINOFFERINGID           ,
        G403_PAYTYPE                  ,
        G404_CHARGINGTYPE             ,
        G412_SERVICETYPE              ,
        G429_RATTYPE                  ,
        G430_CHARGEPARTYINDICATOR     ,
        G432_PRIMARYOFFERCHGAMT       ,
        G435_TAXINFO                  ,
        SUM(G446_PAY_FREE_UNIT_FLUX)       ,
        SUM(G447_PAY_FREE_UNIT_DURATION)   ,
        SUM(G448_PAY_DEBIT_AMOUNT )        ,
        SUM(G449_PAY_DEBIT_FROM_PREPAID)   ,
        SUM(G450_PAY_PREPAID_BALANCE )     ,
        SUM(G453_PAY_POSTPAID_BALANCE)     ,
        G455_SUBSCRIBERIDTYPE         ,
        G467_ACCUMLATEDPOINT,
        G383_CHARGINGTIME_HOUR,
        G388_IMEI,
        G418_LASTEFFECTOFFERING         ,
        COUNT(ETL_DATE_KEY)
        FROM L2_DATA@DWH05TODWH01
        WHERE ETL_DATE_KEY= VDATE_KEY
        GROUP BY 
        ETL_DATE_KEY                  ,
        G372_CALLINGPARTYNUMBER       ,
        G375_CALLINGPARTYIMSI         ,
        G379_CALLINGCELLID            ,
        G383_CHARGINGTIME_KEY         ,
        G389_SERVICEID                ,
        G401_MAINOFFERINGID           ,
        G403_PAYTYPE                  ,
        G404_CHARGINGTYPE             ,
        G412_SERVICETYPE              ,
        G429_RATTYPE                  ,
        G430_CHARGEPARTYINDICATOR     ,
        G432_PRIMARYOFFERCHGAMT       ,
        G435_TAXINFO                  ,
        G455_SUBSCRIBERIDTYPE         ,
        G467_ACCUMLATEDPOINT,
        G383_CHARGINGTIME_HOUR,
        G388_IMEI,
        G418_LASTEFFECTOFFERING;                          
        COMMIT;
        UPDATE ETL_LOG@DWH05TODWH01 SET STATUS = 96,
        UPDATE_TIME=SYSDATE
        WHERE DATE_KEY = VDATE_KEY
        AND LAYER = 'L3_DATA';        
        COMMIT;
       END IF;
   ELSE
     INSERT INTO ETL_LOG@DWH05TODWH01 (LAYER, DATE_KEY, SOURCE, STATUS, INSERT_TIME)
     VALUES              ('L3_DATA',VDATE_KEY,'data','34',SYSDATE);
     COMMIT;
   END IF;
EXCEPTION
 WHEN OTHERS THEN NULL;
END;
/

