--
-- IPDR_INVESTIGATION  (Procedure) 
--
CREATE OR REPLACE PROCEDURE DWH_USER.IPDR_INVESTIGATION AS
BEGIN
INSERT INTO IPDR_FILE_ID_22
SELECT FILE_ID
FROM(
SELECT /*+PARALLEL(P,15)*/  FILE_ID
FROM L1_HUAWEIUDN P
WHERE PROCESSED_DATE BETWEEN TO_DATE(SYSDATE-1,'DD/MON/RRRR') AND TO_DATE(SYSDATE,'DD/MON/RRRR')
UNION ALL
SELECT /*+PARALLEL(Q,15)*/  FILE_ID
FROM L1_HUAWEIUDN2 Q
WHERE PROCESSED_DATE BETWEEN TO_DATE(SYSDATE-1,'DD/MON/RRRR') AND TO_DATE(SYSDATE,'DD/MON/RRRR')
)
WHERE FILE_ID NOT IN (SELECT DISTINCT FILE_ID FROM IPDR_FILE_ID_22)
GROUP BY FILE_ID;
COMMIT;

END;
/

