--
-- P_SUBPARTITION_LOG  (Procedure) 
--
CREATE OR REPLACE PROCEDURE DWH_USER.P_SUBPARTITION_LOG IS
BEGIN
INSERT INTO DWH_USER.SUBPARTITION_LOG
SELECT A.SUBPARTITION_NAME, SYSDATE, 'N'
FROM(
SELECT SUBPARTITION_NAME, RANK () OVER( ORDER BY SUBPARTITION_NAME DESC) SL
FROM USER_TAB_SUBPARTITIONS
)A
WHERE SL <25
AND SUBPARTITION_NAME NOT IN ( SELECT SUBPARTITION_NAME FROM DWH_USER.SUBPARTITION_LOG);
COMMIT;
END;
/

