--
-- R_SHAHIN_IPDR_TABLE  (Procedure) 
--
CREATE OR REPLACE PROCEDURE DWH_USER.R_SHAHIN_IPDR_TABLE IS
    VDATE_KEY       NUMBER;
BEGIN

SELECT DATE_KEY INTO VDATE_KEY
FROM DATE_DIM WHERE TO_CHAR(DATE_VALUE,'RRRRMMDD')=TO_CHAR(SYSDATE-1,'RRRRMMDD');



    --EXECUTE IMMEDIATE  'TRUNCATE TABLE PKPI DROP STORAGE';
    --EXECUTE IMMEDIATE 'ALTER TABLE PKPI TRUNCATE PARTITION PKPI_||VDATE_KEY DROP STORAGE';
    
--DELETE SHAHIN_IPDR_TABLE WHERE DATE_KEY=VDATE_KEY;
--COMMIT;
    
INSERT INTO SHAHIN_IPDR_TABLE




SELECT IP1_STARTTIME,IP2_ENDTIME,IP7_MSISDN,IP10_CGI, IP11_SAI,IP12_ECGI, IP23_UPLINK_TRAFFIC, IP24_DOWNLINK_TRAFFIC, 
     IP14_RAT_TYPE, IP19_RAI, IP20_TAI, IP22_LAI, IP37_SAC, IP38_LAC,DURATION ,VDATE_KEY
     FROM
(SELECT * FROM
(SELECT /*+PARALLEL(P,14)*/ TO_TIMESTAMP( IP1_STARTTIME, 'yyyymmddhh24miss' )IP1_STARTTIME, TO_TIMESTAMP( IP2_ENDTIME, 'yyyymmddhh24miss' )IP2_ENDTIME, 
     IP7_MSISDN, IP10_CGI, IP11_SAI,IP12_ECGI, IP23_UPLINK_TRAFFIC, IP24_DOWNLINK_TRAFFIC, 
     IP14_RAT_TYPE, IP19_RAI, IP20_TAI, IP22_LAI, IP37_SAC, IP38_LAC,
     TO_TIMESTAMP( IP2_ENDTIME, 'yyyymmddhh24miss' ) - TO_TIMESTAMP( IP1_STARTTIME, 'yyyymmddhh24miss' ) DURATION 
FROM 
(SELECT /*+PARALLEL(P,14)*/ *  FROM L1_HUAWEIUDN P
WHERE IP5_SERVER_IP IN (SELECT IP_ADDRESS FROM IP_IPDR)
AND PROCESSED_DATE=TO_DATE(SYSDATE-1,'dd/mon/RRRR')
AND (SUBSTR(IP1_STARTTIME,1,8)=TO_CHAR(SYSDATE-1,'RRRRMMDD'))

) P
)
UNION ALL
(SELECT /*+PARALLEL(P,14)*/ TO_TIMESTAMP( IP1_STARTTIME, 'yyyymmddhh24miss' )IP1_STARTTIME, TO_TIMESTAMP( IP2_ENDTIME, 'yyyymmddhh24miss' )IP2_ENDTIME, 
     IP7_MSISDN, IP10_CGI, IP11_SAI,IP12_ECGI, IP23_UPLINK_TRAFFIC, IP24_DOWNLINK_TRAFFIC, 
     IP14_RAT_TYPE, IP19_RAI, IP20_TAI, IP22_LAI, IP37_SAC, IP38_LAC,
     TO_TIMESTAMP( IP2_ENDTIME, 'yyyymmddhh24miss' ) - TO_TIMESTAMP( IP1_STARTTIME, 'yyyymmddhh24miss' ) DURATION  
FROM 
(SELECT /*+PARALLEL(P,14)*/ *  FROM L1_HUAWEIUDN2 P
WHERE IP5_SERVER_IP IN (SELECT IP_ADDRESS FROM IP_IPDR)
AND PROCESSED_DATE=TO_DATE(SYSDATE-1,'dd/mon/RRRR')
AND (SUBSTR(IP1_STARTTIME,1,8)=TO_CHAR(SYSDATE-1,'RRRRMMDD'))

) P
)
)
;
    COMMIT;
END;
/

